### ISSUE TITLE
call home not working with new devel libraries 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#148] opened 2017-05-30 13:16 UTC
Hi Michal ,

we updated to the latest  devel libraries ( libyang , netopeer,sysrepo,libnetconf2)  and call home is NOT working .
After the callhome configuration is done ( ietf-netconf-server )connection packets are not sent outside to connect with the tcp server .

**Comment by michalvasko** [comment] 2017-05-30 13:29
Hi,
I have just tried it with the most recent libraries and applications, it worked just fine for me... Can you provide some details?

Regards,
Michal

**Comment by vishalwc** [comment] 2017-05-30 13:37
please let me know what kids of detail so that I can provide you with logs .

- the ietf-netconf-server has the configuration of IP and port 
which essentially should start the tcp connection .

**Comment by michalvasko** [comment] 2017-05-30 13:42
The output from *netopeer2-server* with `-v3` from the point of configuring the Call Home should be a good place to start.

**Comment by vishalwc** [comment] 2017-05-30 13:51
May 30 08:56:44 MaestrOS netopeer2-server[30387]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
May 30 08:56:44 MaestrOS netopeer2-server[30387]: Listening on 0.0.0.0:830 for SSH connections.

**Comment by vishalwc** [comment] 2017-05-30 13:52
Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-inet-types               | 2013-07-15 | Installed   |                     |             |                               |
ietf-yang-types               | 2013-07-15 | Installed   |                     |             |                               |
ietf-netconf-monitoring       | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-netconf-acm              | 2012-02-22 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Installed   | root:root           | 666         |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               | if-mib
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-netconf-with-defaults    | 2011-06-01 | Installed   |                     |             |                               |
ietf-system                   | 2014-08-06 | Installed   | root:root           | 666         |                               |
iana-crypt-hash               | 2014-08-06 | Installed   |                     |             |                               |
ietf-keystore                 | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server           | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen call-home ssh-call-home
ietf-x509-cert-to-name        | 2014-12-10 | Imported    |                     |             |                               |
ietf-ssh-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |

**Comment by vishalwc** [comment] 2017-05-30 13:53
```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>test_ssh_listen_endpt</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>test_ssh_listen_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
  <call-home>
    <netconf-client>
      <name>Connector1</name>
      <ssh>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
        <endpoints>
          <endpoint>
            <name>ed0</name>
            <address>10.1.23.193</address>
            <port>4334</port>
          </endpoint>
        </endpoints>
      </ssh>
      <connection-type>
        <persistent>
          <idle-timeout>280</idle-timeout>
          <keep-alives>
            <max-wait>30</max-wait>
            <max-attempts>3</max-attempts>
          </keep-alives>
        </persistent>
      </connection-type>
      <reconnect-strategy>
        <max-attempts>4</max-attempts>
        <start-with>last-connected</start-with>
      </reconnect-strategy>
    </netconf-client>
  </call-home>
</netconf-server>
'''

**Comment by michalvasko** [comment] 2017-05-30 14:02
Please provide the output of executing `cmake` for *netopeer2-server* (first remove `CMakeCache.txt` so that it is complete).

**Comment by vishalwc** [comment] 2017-05-30 14:18
bash-4.2$ cmake -DCMAKE_BUILD_TYPE=Release ../server/
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- Failed to learn keystored keys directory, rerun cmake and set KEYSTORED_KEYS_DIR manually or the server configuration will not wo                                                                      rk.
-- Server configuration off, default SSH host key will be used.
-- Default host key set to "/etc/ssh/ssh_host_rsa_key".
-- Unable to learn libnetconf2 thread support, check skipped
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: /usr/lib64/libsysrepo.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vishalc/Netconf_work/CESNET/Netopeer2/build-server

**Comment by vishalwc** [comment] 2017-05-30 14:55
after this also it give an error 
export KEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys/

**Comment by vishalwc** [comment] 2017-06-12 07:08
Hi Michal 

I assume you are working on this issue and soon we will get the solution , we have come long way 
using your library and would be helpful that we get the solution for this merge .

**Comment by michalvasko** [comment] 2017-06-12 07:48
Hi,
I am sorry for not replying sooner, I was away. If you cannot install `keystored.pc` pkg-config file for some reason (part of *keystored* installation), set the value manually not with `export`, but in `cmake`:
```
cmake -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys/ .
```

Regards,
Michal

**Comment by rosy8** [comment] 2017-06-26 11:03
Hi Michal,

With the latest library, I used the "cmake -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys/ " as specified by you while doing make..and it went fine as shown below...
But getting the following error while running netopeer2-server

 netopeer2-server[27769]: Accepted a connection on 0.0.0.0:830.
netopeer2-server[27769]: Failed to set hostkey "ssh_host_rsa_key" ().
netopeer2-server[27769]: Accepted a connection on 0.0.0.0:830.
netopeer2-server[27769]: Failed to set hostkey "ssh_host_rsa_key" ().

By looking at the code, I could see we are getting this from func ("nc_ssh_bind_add_hostkeys"). 
File:-libnetconf2/src/session_server_ssh.c
========>>
cmake -D CMAKE_BUILD_TYPE:String="Debug" .. -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/
keys/.. && make 

-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- keystored keys directory is "/usr/local/etc/keystored/keys/..".
-- Unable to learn libnetconf2 thread support, check skipped
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: /usr/local/lib64/libsysrepo.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/haripriyap/gitcode_devel/Netopeer2/server/build
Scanning dependencies of target serverobj
Scanning dependencies of target serverobj
[  6%] Building C object CMakeFiles/serverobj.dir/ietf_netconf_server.c.o
[ 12%] Building C object CMakeFiles/serverobj.dir/ietf_system.c.o
[ 18%] Building C object CMakeFiles/serverobj.dir/ietf_keystore.c.o
[ 25%] Building C object CMakeFiles/serverobj.dir/netconf_monitoring.c.o
[ 31%] Building C object CMakeFiles/serverobj.dir/operations.c.o
[ 37%] Building C object CMakeFiles/serverobj.dir/op_get_config.c.o
[ 43%] Building C object CMakeFiles/serverobj.dir/op_editconfig.c.o
[ 50%] Building C object CMakeFiles/serverobj.dir/op_copyconfig.c.o
[ 56%] Building C object CMakeFiles/serverobj.dir/op_deleteconfig.c.o
[ 62%] Building C object CMakeFiles/serverobj.dir/op_candidate.c.o
[ 68%] Building C object CMakeFiles/serverobj.dir/op_validate.c.o
[ 75%] Building C object CMakeFiles/serverobj.dir/op_un_lock.c.o
[ 81%] Building C object CMakeFiles/serverobj.dir/op_generic.c.o
[ 87%] Building C object CMakeFiles/serverobj.dir/op_notifications.c.o
[ 93%] Building C object CMakeFiles/serverobj.dir/log.c.o
[ 93%] Built target serverobj
Scanning dependencies of target netopeer2-server
[100%] Building C object CMakeFiles/netopeer2-server.dir/main.c.o
Linking C executable netopeer2-server
[100%] Built target netopeer2-server

Please let me know if I have missed anything here.
Thanks in advance.

Regards,
Rosy

**Comment by rosy8** [comment] 2017-06-27 05:06
Hi Michal,

Would appreciate if you could give some info/input on this .

Regards,
Rosy

**Comment by michalvasko** [comment] 2017-06-27 16:10
Hi Rosy,
I think there will be some configuration problem, but I want to try this myself and at least display a proper error message and I have quite limited options until Thursday, so I will definitely look at it then. For now I can ask you whether you installed *keystored* (why did you have to set the path manually?) and whether you have *sysrepo-plugind* running.

Regards,
Michal

**Comment by rosy8** [comment] 2017-06-29 05:26
Hi Michal,

Yeah , I had installed keystored.
After I executed sysrepo-plugind, I am not getting the "Failed to set hostkey "ssh_host_rsa_key" ()." error.

But I am not able perform edit-config as shown below and sometimes sysrepo process is failing too.

netopeer2-server[9607]: Resolving unresolved data nodes and their constraints...
netopeer2-server[9607]: All data nodes and constraints resolved.
netopeer2-server[9607]: Session 1: thread 0 event new RPC.
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
netopeer2-server[9607]: Resolving unresolved data nodes and their constraints...
netopeer2-server[9607]: All data nodes and constraints resolved.
[INF] (rp_dt_set_item_wrapper:575) Set item request candidate datastore, xpath: /xyz-config:abc-config/xyz-rate-profile:rate-profiles/rate-profile[name='Haripriya']
[INF] (rp_dt_set_item_wrapper:575) Set item request candidate datastore, xpath: /xyz-config:abc-config/xyz-rate-profile:rate-profiles/rate-profile[name='Haripriya']/color-enabled
[INF] (dm_unlock_datastore:1540) Unlock datastore request
netopeer2-server[9607]: Session 1: thread 0 event new RPC.
[INF] (dm_unlock_datastore:1540) Unlock datastore request
netopeer2-server[9607]: Session 1: thread 0 event new RPC.

Regards,
Rosy

**Comment by michalvasko** [comment] 2017-06-29 06:36
Hi Rosy,
the commit should be fixed in `devel-server` branch (the change is only in *sysrepo* devel branch). But I am not sure what you mean by "sometimes sysrepo process is failing too", could you elaborate?

Regards,
Michal

**Comment by rosy8** [comment] 2017-06-29 10:28
Hi Michal.

In the debug-log, I used to get sysrepo failed message which I am not getting anymore now.
I did not find any changes in sysrepo, rather i could see changes are in Netopeer2.

But after integrating with the new library I am again getting the same old error "Failed to set hostkey "ssh_host_rsa_key" ()."  :( (which I find quite strange. Because the fix which you have given should not have any impact on  this ) 
**netopeer2-server[12299]: Accepted a connection on 0.0.0.0:830.
netopeer2-server[12299]: Failed to set hostkey "ssh_host_rsa_key" ().**

 I have installed keystored and have executed sysrepo-plugind as I had done earlier.
[root@xyz ~]# ps -aef | grep -iE "sysre|neto"
root     12294  6924  0 13:16 pts/0    00:00:01 sysrepod -d -l 3
root     12299  6924  0 13:16 pts/0    00:00:04 netopeer2-server -d -v 3
root     12338     1  0 13:17 ?        00:00:00 ./sysrepo-plugind
root     12395  6924  0 13:17 pts/0    00:00:00 sysreposync


Please let me know if I am missing anything here.

Regards,
Rosy

**Comment by michalvasko** [comment] 2017-07-03 07:26
Hi Rosy,
please pull recent `devel` *libnetconf2* (0.9.6), apply attached patch, try again to receive the same error, and please post the output here, there should some new messages, thanks.

Regards,
Michal
[debug.patch.txt](https://github.com/CESNET/Netopeer2/files/1118732/debug.patch.txt)

**Comment by rosy8** [comment] 2017-07-03 09:49
Hi Michal,

Thanks for working on it.
I followed the steps as you had mentioned and now I am getting the error msgs as shown below..

Jul  3 12:50:55  netopeer2-server[16026]: Accepted a connection on 0.0.0.0:830.
Jul  3 12:50:55  netopeer2-server[16026]: # 1 path "/usr/local/etc/keystored/keys/../ssh_host_rsa_key.pem", data "(null)", rsa 0
Jul  3 12:50:55  netopeer2-server[16026]: # 2 path "/usr/local/etc/keystored/keys/../ssh_host_rsa_key.pem", data "(null)", rsa 0
Jul  3 12:50:55  netopeer2-server[16026]: # access path -1, error Success
Jul  3 12:50:55  netopeer2-server[16026]: Failed to set hostkey "ssh_host_rsa_key" (-1: ).

Regards,
Rosy

**Comment by michalvasko** [comment] 2017-07-10 09:34
Hi Rosy,

sorry I did not respond and actually didn't notice the problem before. You used wrong *keytored* keys directory because you added `..` I did not mention. Please, change
```
cmake -D CMAKE_BUILD_TYPE:String="Debug" .. -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys/.. && make
```
to
```
cmake -D CMAKE_BUILD_TYPE:String="Debug" .. -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys/ && make
```

You must reinstall *keystored* after running `cmake`, of course.

Regards,
Michal

**Comment by vishalwc** [comment] 2017-07-19 07:43
Hi Michal we have one more observation ,
 
Callhome stale entries ( netstats show connection stayed established ) on connector after tcp server disconnects callhome connection .

**Comment by rosy8** [comment] 2017-07-20 07:02
Hi Michal,

With the latest build I could see call-home is working fine. I was able to establish the connection as well as was able to do edit/get/get-config on call home parameters .

[root@cc-107 ~]# netstat -plan | grep 830
tcp        0      0 0.0.0.0:830             0.0.0.0:*               LISTEN      17175/netopeer2-ser
tcp        0      0 10.1.18.107:830         10.1.1.59:42142         ESTABLISHED 17175/netopeer2-ser
[root@cc-107 ~]# netstat -plan | grep 4334
tcp        0      0 10.1.18.107:57766       10.1.23.19:4334         ESTABLISHED 17175/netopeer2-ser
[root@cc-107 ~]#

But I am not able to do get/edit-config on other nodes . Giving example of a simple get on a high level container.

`<get>
  <filter type="subtree">
    <xxxcfg:abc-config xmlns:xxxcfg="http://www.abc.com/ns/xyz-abc-config"/>
  </filter>
</get>`

`<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="8">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Getting items (/xyz-abc-config:abc-config//.) from sysrepo failed (Request contains unknown element).</error-message>
  </rpc-error>
</rpc-reply>`

Jul 20 08:47:44  netopeer2-server[26083]: Resolving unresolved data nodes and their constraints...
Jul 20 08:47:44  netopeer2-server[26083]: All data nodes and constraints resolved.
Jul 20 08:47:44  sysrepod[17145]: [INF] (rp_dt_refresh_session:1019) Refresh session request running datastore
Jul 20 08:47:44  sysrepod[17145]: [INF] (rp_dt_refresh_session:1031) No operation has been performed on this session so far
Jul 20 08:47:44  sysrepod[17145]: [INF] (rp_dt_get_values_wrapper_with_opts:1356) Get items request running datastore, xpath: /xyz-abc-config:abc-config//., offset: 0, limit: 100
Jul 20 08:47:44  sysrepod[17145]: [INF] (dm_load_data_tree_file:1153) Data file /etc/sysrepo/data/xyz-abc-config.running loaded successfully
Jul 20 08:47:44  sysrepod[17145]: [ERR] (dm_ly_log_cb:1277) libyang error: Schema node "alarm" not found (/xyz-abc-config:abc-config/xyz-test-alarm:alarms/alarm).
Jul 20 08:47:44  sysrepod[17145]: [ERR] (dm_ly_log_cb:1277) libyang error: Resolving XPath expression "/xyz-abc-config:abc-config/xyz-test-alarm:alarms/alarm/alarm-id" failed.
Jul 20 08:47:44  sysrepod[17145]: [ERR] (rp_dt_xpath_requests_state_data:726) Unable to find schema node for /xyz-abc-config:abc-config/xyz-test-alarm:alarms/alarm/alarm-id
Jul 20 08:47:44  sysrepod[17145]: [ERR] (rp_dt_prepare_data:1225) rp_dt_xpath_requests_state_data failed
Jul 20 08:47:44  sysrepod[17145]: [ERR] (rp_dt_get_values_wrapper_with_opts:1369) rp_dt_prepare_data failed
Jul 20 08:47:44  sysrepod[17145]: [ERR] (rp_dt_get_values_wrapper_with_opts:1400) Copying values from nodes failed for xpath '/xyz-abc-config:abc-config//.'
Jul 20 08:47:44  sysrepod[17145]: [ERR] (rp_get_items_req_process:824) Get items failed for '/xyz-abc-config:abc-config//.', session id=636441865.
Jul 20 08:47:44  netopeer2-server[26083]: (cl_request_process:562) Error by processing of the get-items request (session id=636441865): Request contains unknown element.
Jul 20 08:47:44  netopeer2-server[26083]: (sr_get_items_iter:1038) Sending get_items request failed '/xyz-abc-config:abc-config//.'
Jul 20 08:47:44  netopeer2-server[26083]: Getting items (/xyz-abc-config:abc-config//.) from sysrepo failed (Request contains unknown element).
Jul 20 08:47:44  netopeer2-server[26083]: Session 1: thread 0 event new RPC.
Jul 20 08:47:44  netopeer2-server[26083]: Session 1: thread 0 event reply error.

Please let me know if I am missing something here..
Thanks in advance.

Note-I have used insert code. But still do see the xml code in one line. If you cannot get it let me know I will add line by line.

Regards,
Rosy

**Comment by rosy8** [comment] 2017-07-20 07:10
edit-config

`<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config>
      <xyz-config xmlns="http://www.abc.com/ns/aaa-config">
        <rate-profiles xmlns="http://www.abc.com/ns/aaa-rate-profile">
          <rate-profile>
            <name>Test</name>
            <cir>10000000000</cir>
            <eir>0</eir>
            <cbs>1048576</cbs>
            <ebs>16384</ebs>
            <color-enabled>false</color-enabled>
            <coupling-enabled>false</coupling-enabled>
          </rate-profile>
        </rate-profiles>
      </xyz-config>
    </config>
  </edit-config>
</rpc>
`

`<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="71">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-path>/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']</error-path>
    <error-message xml:lang="en">Resolving XPath expression "/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']" failed.</error-message>
  </rpc-error>
</rpc-reply>`

Log--
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: Resolving unresolved data nodes and their constraints...
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: All data nodes and constraints resolved.
Jul 19 16:07:25 cc-107 sysrepod[17145]: [INF] (rp_dt_set_item_wrapper:576) Set item request candidate datastore, xpath: /aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']
Jul 19 16:07:25 cc-107 sysrepod[17145]: [ERR] (dm_ly_log_cb:1277) libyang error: Schema node "rate-profile" not found (/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile).
Jul 19 16:07:25 cc-107 sysrepod[17145]: [ERR] (dm_ly_log_cb:1277) libyang error: Resolving XPath expression "/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']" failed.
Jul 19 16:07:25 cc-107 sysrepod[17145]: [ERR] (rp_dt_set_item:327) Requested node is not valid /aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']
Jul 19 16:07:25 cc-107 sysrepod[17145]: [ERR] (rp_dt_set_item_wrapper:592) Set item failed
Jul 19 16:07:25 cc-107 sysrepod[17145]: [ERR] (rp_set_item_req_process:1197) Set item failed for '/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']', session id=776423864.
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: (cl_request_process:562) Error by processing of the set-item request (session id=776423864): Resolving XPath expression "/aaa-config:xyz-config/aaa-rate-profile:rate-profiles/rate-profile[name='Test']" failed..
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: (sr_set_item:1839) Error by processing of the request.
Jul 19 16:07:25 cc-107 sysrepod[17145]: [INF] (dm_unlock_datastore:1491) Unlock datastore request
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: Session 2: thread 2 event new RPC.
Jul 19 16:07:25 cc-107 netopeer2-server[17175]: Session 2: thread 2 event reply error.

**Comment by michalvasko** [comment] 2017-07-20 07:34
Hi Rosy,
sorry about this, it is most likely caused by recent changes in path addressing, it is a bit of a mess right now. But I am working on it and this particular use-case should be fixed soon, I will let you know.

@vishalwc I will try to look at this later, but it seems to me it is just another "feature" of the TCP/IP stack and not something I can fix, but I will see.

Regards,
Michal

**Comment by rosy8** [comment] 2017-07-20 08:54
Hi Michal,

Thank you very much for replying back.
Yeah please let us know once its fixed and working.

Regards,
Rosy

**Comment by rosy8** [comment] 2017-08-03 09:22
Hi Michal,

Is it resolved ?

Regards,
Rosy

**Comment by michalvasko** [comment] 2017-08-03 12:18
Hi Rosy,
you can actually test it for me if you want, I am still finishing all those path changes (hopefully today, but I will need to merge it to *sysrepo* devel, which with tests takes some time), but this particular problem should be fixed. So, please try it and let me know if I need to test it and fix it after I finish the current changes or it is already working, thanks.

Regards,
Michal

**Closed** 2017-08-14 11:46 UTC
