### ISSUE TITLE
Netopeer reports: Failed to find "address" as a sibling to "ietf-ip:ip".

### ISSUE THREAD

**Issue by vhuertas** [CESNET/netopeer2#421] opened 2019-04-17 16:28 UTC
Hello,

I am using sysrepo and netopeer2-server to configure an ietf-interfaces model with new IPv6 addresses.

When I issue the NETCONF "merge" command the configuration of the IP address is performed well. However, when I try to get the interfaces-state, my application provides correctly the data (where the configured IPv6 address and prefix length is contained) but the netopeer reports and rpc-reply error telling that "[ERR] Failed to find "address" as a sibling to "ietf-ip:ip".

Recently I have updated the netopeer2-server to the lastest version (0.7.11) in the master branch and with the previous version I didn't have any problem.

The logs from netopeer2-server when this problem occurs are:
[INF]: Listening on 0.0.0.0:830 for SSH connections.
[INF]: Accepted a connection on 0.0.0.0:830.
[2019/04/17 18:07:13.521260, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/04/17 18:07:13.522579, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-SSHD-CORE-2.0.0
[2019/04/17 18:07:13.522619, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-SSHD-CORE-2.0.0
[2019/04/17 18:07:13.522702, 2] ssh_kex_select_methods:  Negotiated ecdh-sha2-nistp521,ssh-rsa,aes128-ctr,aes128-ctr,hmac-sha1,hmac-sha1,none,none,,
[2019/04/17 18:07:13.539311, 2] ssh_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2019/04/17 18:07:13.539401, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/04/17 18:07:13.539421, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/04/17 18:07:13.539447, 2] ssh_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2019/04/17 18:07:13.550707, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[2019/04/17 18:07:13.590252, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[INF]: User "root" authenticated.
[INF]: Received an SSH message "request-channel-open" of subtype "session".
[INF]: Received an SSH message "request-channel" of subtype "subsystem".
[2019/04/17 18:07:13.610803, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: Generated new event (netconf-session-start).
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
**[ERR]: Failed to find "address" as a sibling to "ietf-ip:ip".**
[INF]: Session 1: thread 3 event new RPC.
[INF]: Session 1: thread 3 event reply error.

Once I compiled and executed the newest netopeer2-server I realized that the IPv6 key placed in the /ietf-interfaces:interfaces/interface[name='eth0']/ietf-ip:ipv6/address[ip]/ip suddenly had the "compressed" string format of the ipv6 ("fd::62/64" in my example) whereas in the previous version I was using of netopeer the key format was just the one I inserted using the NETCONF client (that is, "fd00:0000:0000:0000:0000:0000:0000:0062"). I realize that with the newest version of netopeer2-server the key format is changed to the "compressed" mode  ("fd::62/64") despite the fact I inserted the non-compressed one ("fd00:0000:0000:0000:0000:0000:0000:0062").

On the other hand, when I provide the "interfaces-state" data from my application, the key I provide for this IP address is always with this format: "fd00:0000:0000:0000:0000:0000:0000:0062". 

Does the netopeer2.-server compare the key in the "interfaces" and the "interfaces-state" sending such an ERROR if it doesn't finds an exact match on both sides? 
"fd00::62" at the operational side doesn't match exactly with "fd00:0000:0000:0000:0000:0000:0000:0062" at the state side ... and perhaps the "sibling" issue comes from here... Am I right?

Thanks for your attention

**Comment by michalvasko** [comment] 2019-04-18 07:42
Hi,
I do not think canonization of the values is the problem. Does *sysrepod* print some errors or warnings (when run with `-d -l3`)? If not, then I would have to reproduce this before I can fix it. Can you maybe share your state data callback? And what is the RPC you sent, just a simple `<get>`?

Regards,
Michal

**Comment by vhuertas** [comment] 2019-04-18 11:59
Hi,

The RPC is a simple get of the '/ietf-interfaces:interfaces-state/interface[name='eth0']'. It used to work fine in my application until I updated netopeer2-server to the very last version.

The state data callback of my application when providing the data is the following:

data_provider_cb: /ietf-interfaces:interfaces-state 
data_provider_cb: /ietf-interfaces:interfaces-state/interface 
[s0: /ietf-interfaces:interfaces-state/interface 
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/name' with value 'eth0'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/type' with value 'iana-if-type:ethernetCsmacd'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/admin-status' with value 'up' 
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status' with value 'up'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/if-index' with value '1'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/phys-address' with value '00:30:48:BB:17:02'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/speed' with value '1000000000'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/forwarding' with value 'false'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/ip' with value 'fd00:0000:0000:0000:0000:0000:0000:0062'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/prefix-length' with value '64'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/origin' with value 'static'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/status' with value 'preferred'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/send-advertisements' with value 'false'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/max-rtr-adv-interval' with value '600'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/managed-flag' with value 'false'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/other-config-flag' with value 'false'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/link-mtu' with value '0'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/reachable-time' with value '0'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/retrans-timer' with value '0'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/name' with value 'eth1'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/type' with value 'iana-if-type:ethernetCsmacd'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/admin-status' with value 'up' 
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/oper-status' with value 'up'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/if-index' with value '2'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/phys-address' with value '00:30:48:BB:17:03'
[NETCONF] providing data '/ietf-interfaces:interfaces-state/interface[name='eth1']/speed' with value '1000000000'


At sysrepo, no ERR or WRN logs are displayed except for these ones:

[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/name'.
[DBG] Module ietf-interfaces already loaded
[ERR] Value of the key can not be set /ietf-interfaces:interfaces-state/interface[name='eth0']/name
[WRN] Failed to set operational data for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/name'.
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/type'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/admin-status'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/if-index'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/phys-address'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/speed'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/forwarding'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/ip'.
[DBG] Module ietf-interfaces already loaded
[ERR] Value of the key can not be set /ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/ip
[DBG] Overwriting session error message Value of the key can not be set
[DBG] Overwriting session error xpath /ietf-interfaces:interfaces-state/interface[name='eth0']/name
[WRN] Failed to set operational data for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/ip'.
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/prefix-length'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/origin'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/status'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/send-advertisements'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/max-rtr-adv-interval'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/managed-flag'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/other-config-flag'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/link-mtu'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/reachable-time'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements/retrans-timer'.
[DBG] Module ietf-interfaces already loaded
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth1']/name'.
[DBG] Module ietf-interfaces already loaded
[ERR] Value of the key can not be set /ietf-interfaces:interfaces-state/interface[name='eth1']/name
[DBG] Overwriting session error message Value of the key can not be set
[DBG] Overwriting session error xpath /ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address[ip='fd00:0000:0000:0000:0000:0000:0000:0062']/ip
[WRN] Failed to set operational data for xpath '/ietf-interfaces:interfaces-state/interface[name='eth1']/name'.
[DBG] Received value from data provider for xpath '/ietf-interfaces:interfaces-state/interface[name='eth1']/type'.

Please note that these ERR logs were already present in the previsous version I used of netopeer2-server but, the rpc reply was OK. So I don't know if this could be the cause.

Regards,

**Comment by michalvasko** [comment] 2019-04-18 12:16
Hi,
so to get rid of *sysrepod* errors, you should just need to not to return list keys. But I agree that they should not be causing any problems. Then you can try what you suggested, to return canonical IP address values and see whether that fixes the error. If so, then I will try to fix it so that it is not necessary.

Regards,
Michal

**Comment by vhuertas** [comment] 2019-04-18 12:52
Thanks Michal,
I will try to do it before Easter holidays but if I do not have enough time I will have to test it next week.
This issue is important for us as it would block the development of a project in which we are using sysrepo and netopeer2-server.
Step by step let's find a solution and improve the netopeer2-server as well as sysrepo softwares.

Regards,

**Comment by michalvasko** [comment] 2019-04-23 10:02
Hi,
we have changed it for the values to be transformed to canonical format because of an [RFC requirement](https://tools.ietf.org/html/rfc7950#section-9.1). But, strictly speaking, *sysrepo* is not bound by this RFC. Anyway, I have pushed a fix in *libyang* that should improve things, it fixed a problem I have encountered but it was different from yours. So, please try it and report back. Then we can discuss a proper fix.

Regards,
Michal

**Closed** 2020-05-15 06:37 UTC
