### ISSUE TITLE
copy-config with <source> <config> Failed for a module with sub-modules.

### ISSUE THREAD

**Issue by darshana-jk** [CESNET/Netopeer2#223] opened 2018-02-21 05:33 UTC
We are trying to invoke copy-config via Netopeer2-server for bbf-vdsl and it fails to delete in the sysrepo with the error:

sysrepod[1585]: [ERR] Delete item failed for '/bbf-vdsl-base:*', session id=1462771036.
netopeer2-server[2436]: Error by processing of the delete-item request (session id=1462771036): Invalid argument.
netopeer2-server[2436]: Error by processing of the request.
netopeer2-server[2436]: np2srv_sr_delete_item failed (sysrepo: Invalid argument).
netopeer2-server[2436]: Session 1: thread 3 event new RPC.

We have this module installed in sysrepo too:
```
sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-acm              | 2012-02-22 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Imported    |                     |             |                               |
ietf-keystore                 | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name        | 2014-12-10 | Installed   |                     |             |                               |
ietf-netconf-server           | 2016-11-02 | Installed   | root:root           | 666         |                               | call-home tls-call-home
ietf-ssh-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                   | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash               | 2014-08-06 | Imported    |                     |             |                               |
iana-if-type                  | 2017-03-30 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               | if-mib
bbf-vdsl                      | 2017-03-13 | Installed   | root:root           | 666         |  bbf-vdsl-base-body bbf-vdsl-test-mode-body bbf-vdsl-channel-body bbf-vdsl-base bbf-vdsl-line bbf-vdsl-inventory-body bbf-vdsl-xtu bbf-vdsl-data-rate-profile-body bbf-vdsl-service-profiles bbf-vdsl-line-spectrum-profile-body bbf-vdsl-mode-specific-psd-profile-body bbf-vdsl-upstream-power-back-off-profile-body bbf-vdsl-downstream-power-back-off-profile-body bbf-vdsl-radio-frequency-interference-profile-body bbf-vdsl-spectrum-profiles bbf-vdsl-noise-margin-profile-body bbf-vdsl-impulse-noise-protection-delay-profile-body bbf-vdsl-virtual-noise-profile-body bbf-vdsl-sos-profile-body bbf-vdsl-impulse-noise-monitoring-profile-body bbf-vdsl-re-initialization-policy-profile-body bbf-vdsl-vectoring-profile-body bbf-vdsl-data-gathering-profile-body bbf-vdsl-quality-profiles bbf-vdsl-line-status-body bbf-vdsl-xtu-line-status-body bbf-vdsl-xtu-band-status-body bbf-vdsl-xtu-annex-c-status-body bbf-vdsl-xtu-channel-status-body bbf-vdsl-status-monitoring bbf-vdsl-xtu-line-performance-body bbf-vdsl-xtu-channel-performance-body bbf-vdsl-performance-management bbf-vdsl-xtu-line-threshold-profile-body bbf-vdsl-xtu-channel-threshold-profile-body bbf-vdsl-threshold-management bbf-vdsl-xtu-sub-carrier-status-body bbf-vdsl-xtu-data-gathering-report-body bbf-vdsl-test-diagnostics bbf-vdsl-pointers|
bbf-fastdsl                   | 2017-03-13 | Implemented |                     |             |                               |
bbf-yang-types                | 2016-07-18 | Imported    |                     |             |                               |
```

**Steps to Reproduce**

1. Build the latest packages (sysrepo, libyang, libnetconf2, Netopeer2). Note the sysrepo example build is disabled, as it installs other YANGs.

2. Load YANG modules - use [data.tar.gz](https://github.com/sysrepo/sysrepo/files/1701926/data.tar.gz), the ./load-bbf-vdsl.sh script will load all the required modules and data.
bbf-vdsl and ietf-interfaces are loaded.

3. Send the copy-config RPC:
```
<copy-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <source>
    <config>
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface>
          <name>dsl-1</name>
          <description>Port 1</description>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:fastdsl</type>
          <enabled>true</enabled>
          <line xmlns="urn:bbf:yang:bbf-fastdsl">
            <configured-mode>mode-vdsl</configured-mode>
            <line xmlns="urn:bbf:yang:bbf-vdsl">
              <test-mode>
                <power-management-state-forced>0</power-management-state-forced>
                <loop-diagnostics-mode-forced>0</loop-diagnostics-mode-forced>
                <auto-mode-cold-start-forced>0</auto-mode-cold-start-forced>
              </test-mode>
            </line>
          </line>
        </interface>
      </interfaces>
    </config>
  </source>
</copy-config>
```
Error:
```
sysrepod[1585]: [ERR] Delete item failed for '/bbf-vdsl-base:*', session id=1462771036.
netopeer2-server[2436]: Error by processing of the delete-item request (session id=1462771036): Invalid argument.
netopeer2-server[2436]: Error by processing of the request.
netopeer2-server[2436]: np2srv_sr_delete_item failed (sysrepo: Invalid argument).
netopeer2-server[2436]: Session 1: thread 3 event new RPC.
```

**We think the reason for the behaviour is:**
The function `np2srv_sr_delete_item` in op_copyconfig.c gets the wrong path `/bbf-vdsl-base:*` when it should've received `/bbf-vdsl:*`. This only happens for bbf-vdsl module and other modules like ietf-interfaces, ietf-netconf-server etc resolved fine. We tried modifying the code by building the path string using ```lys_module->prefix``` instead and it worked correctly for the bbf-vdsl module. We suspect the bbf-vdsl being a module with a set of submodule could be the difference. 

**Some debugging (We logged the lys_node objects being considered for delete.):**

netopeer2-server[29276]: Resolving unresolved data nodes and their constraints...
netopeer2-server[29276]: All data nodes and constraints resolved.
netopeer2-server[29276]: name = interfaces
netopeer2-server[29276]:   node->nodetype = 1
netopeer2-server[29276]:   node->prefix = if, node->module = ietf-interfaces
netopeer2-server[29276]:     sibling = interfaces-state - ietf-interfaces
netopeer2-server[29276]: name = vdsl
netopeer2-server[29276]:   node->nodetype = 1
netopeer2-server[29276]:   node->prefix = bbf-vdsl, node->module = bbf-vdsl-base < WRONG MODULE NAME HERE>
netopeer2-server[29276]:     sibling = inventory - bbf-vdsl-inventory-body
netopeer2-server[29276]:     sibling = vce - bbf-vdsl-inventory-body
netopeer2-server[29276]:     sibling = data-rate-profile - bbf-vdsl-data-rate-profile-body
netopeer2-server[29276]:     ...
netopeer2-server[29276]:     ...

**Versions we had to test: ( Tried running this in the latest version of sysrepo+libyang+Neopeer+libnetconf, the resolve function in libyang caused SIGSEGV.
)**

Git repo libyang
commit abe7c323a7a4a51485433eafb46210fd64a04206
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Nov 21 13:43:44 2017 +0100

    VERSION bump to version 0.14.46
Git repo libnetconf2
commit 262067e50f03aa2effdbf203842679c9cf3838c3
Author: Radek Krejci <rkrejci@cesnet.cz>
Date:   Wed Nov 8 12:51:10 2017 +0100

    VERSION bump version to 0.10.16
Git repo sysrepo
commit 916a99ff29ef8cb792f084d8fb863b9683e6d1df
Merge: 1d73be9 514b92b
Author: Mislav Novakovic <mislav.novakovic@gmail.com>
Date:   Tue Nov 21 13:45:45 2017 +0100

    Merge pull request #990 from sartura/cpp_refactoring
    
    Cpp refactoring
Git repo Netopeer2
commit 433be88aad3bdfab2ae5686a429c5d39eb85ffc3
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Nov 20 15:07:30 2017 +0100

    server VERSION bump to version 0.4.12

**Comment by michalvasko** [comment] 2018-02-21 09:44
Hi Darshana,
you said you tried this in the `devel` versions and it crashed? You should have reported that first. However, I have tried this locally with `devel`s and it worked fine for me. So, please try it with the most recent versions and report any problems you encounter.

Regards,
Michal

**Comment by unmanned-player** [comment] 2018-02-22 02:08
Hello Michal,

I'm sorry, we had tried meant the latest shown in the release page. Not the devel latest. 
Now we tried it on devel latest and ran into the same problem:

Versions (devel branch):
libnetconf2: `5953dc129542d76d6ee835e1e9082cac72f258b0`
libyang: `12e47ade8c6133fb014a1160259c93a4ee5005b9`
Netopeeer2: `e127328c3ef3a4373fe7bea2056b507beaaad50a`
sysrepo: `890e759b208b7712026a6dd8a0036a4e0b3d209f`

The correct XML (rpc) to reproduce the issue is shown below (this is because we need `bbf-vdsl` objects to produce the issue):

```
<copy-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <source>
    <config>
      <vdsl xmlns="urn:bbf:yang:bbf-vdsl">
        <service>
          <downstream-data-rate-profile>
            <name>datarate_profile_ds</name>
            <minimum-net-data-rate>32000</minimum-net-data-rate>
            <maximum-net-data-rate>200000000</maximum-net-data-rate>
            <maximum-bit-error-ratio>1e-7</maximum-bit-error-ratio>
            <minimum-expected-throughput-rtx>64000</minimum-expected-throughput-rtx>
            <maximum-expected-throughput-rtx>100000000</maximum-expected-throughput-rtx>
            <maximum-net-data-rate-rtx>108000000</maximum-net-data-rate-rtx>
          </downstream-data-rate-profile>
          <upstream-data-rate-profile>
            <name>datarate_profile_us</name>
            <minimum-net-data-rate>32000</minimum-net-data-rate>
            <maximum-net-data-rate>100000000</maximum-net-data-rate>
            <maximum-bit-error-ratio>1e-7</maximum-bit-error-ratio>
            <minimum-expected-throughput-rtx>64000</minimum-expected-throughput-rtx>
            <maximum-expected-throughput-rtx>43600000</maximum-expected-throughput-rtx>
            <maximum-net-data-rate-rtx>43800000</maximum-net-data-rate-rtx>
          </upstream-data-rate-profile>
        </service>
      </vdsl>
    </config>
  </source>
</copy-config>
```
We still get the same error in devel latest.
```
netopeer2-server[31328]: All data nodes and constraints resolved.
netopeer2-server[31328]: (cl_request_process:562) Error by processing of the delete-item request (session id=923661922): Invalid argument.
netopeer2-server[31328]: (sr_delete_item:1947) Error by processing of the request.
```

And on sysrepo side:
```
sysrepod[14028]: [WRN] (ac_check_file_access:129) File '/etc/sysrepo/data/bbf-vdsl-base.startup' cannot be found.
sysrepod[14028]: [WRN] (ac_check_module_node_permissions:289) Data file '/etc/sysrepo/data/bbf-vdsl-base.startup' not found, considering as authorized.
sysrepod[14028]: [WRN] (dm_load_module:916) An attempt to load submodule bbf-vdsl-base
sysrepod[14028]: [ERR] (dm_free_schema_info:276) NULL value detected for schema_info argument of dm_free_schema_info
sysrepod[14028]: [ERR] (dm_get_data_info_internal:2652) Get module 'bbf-vdsl-base' failed
sysrepod[14028]: [ERR] (rp_dt_delete_item:195) Getting data tree failed for xpath '/bbf-vdsl-base:*'
sysrepod[14028]: [ERR] (rp_dt_delete_item_wrapper:618) List delete failed
sysrepod[14028]: [ERR] (rp_delete_item_req_process:1305) Delete item failed for '/bbf-vdsl-base:*', session id=1684803360.
```

Again, it picked the wrong module. It should have picked `bbf-vdsl` and not `bbf-vdsl-base` which is only a sub-module. We expect sysrepo to delete `bbf-vdsl`.

**Comment by michalvasko** [comment] 2018-02-22 08:52
Hi Anandu,
with this `copy-config` I reproduced it and it should be fixed, thanks.

Regards,
Michal

**Closed** 2018-02-22 08:52 UTC
