### ISSUE TITLE
Invalid leafref value error in ietf-keystore module

### ISSUE THREAD

**Issue by j1y3p4rk** [CESNET/netopeer2#949] opened 2021-07-07 13:48 UTC
Hi, I could successfully merge the tls_keystore.xml and tls_truststore.xml files. 
When I am trying to merge 'tls_listen.xml file, I see an invalid leafref value error as below.
I couldn't find similar issue. Did I miss something or I need to change something? 

```
ubuntu@ip-172-31-8-184:~/netopeer2/example_configuration$ sysrepocfg --edit=tls_listen.xml -m ietf-netconf-server -d startup -v4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Connection 94 created.
[INF]: Session 474 (user "ubuntu", CID 94) created.
[ERR]: Invalid leafref value "servercert" - no existing target instance "/ks:keystore/ks:asymmetric-keys/ks:asymmetric-key[ks:name = current()/../asymmetric-key]/ks:certificates/ks:certificate/ks:name".
[ERR]: Validation failed.
sysrepocfg error: Failed to merge edit data (Validation failed)
[INF]: No write permission for the module "ietf-yang-library", skipping.
[INF]: No write permission for the module "sysrepo-monitoring", skipping.
[INF]: No write permission for the module "sysrepo-plugind", skipping.
[INF]: No datastore changes to apply.
```

**Comment by michalvasko** [comment] 2021-07-08 14:19
Duplicate of https://github.com/sysrepo/sysrepo/issues/2507.

**Closed** 2021-07-08 14:19 UTC
Labels: status:duplicate
