### ISSUE TITLE
fatal error: openssl/x509.h: No such file or directory

### ISSUE THREAD

**Issue by mx568549060** [CESNET/netopeer2#1314] opened 2022-12-04 15:41 UTC
My problems seems same as https://github.com/CESNET/netopeer2/issues/1312 , I have fix the bug CMakeLists.txt but error still appear.

```
hc@ubuntu:~/netconf/netopeer2-2.1.36/build$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/install/usr/local  -DLIBYANG_LIBRARY=/home/hc/netconf/libyang-2.0.231/build/install/usr/local/lib/libyang.so  -DLIBYANG_INCLUDE_DIR=/home/hc/netconf/libyang-2.0.231/build/install/usr/local/include  -DLIBNETCONF2_LIBRARY=/home/hc/netconf/libnetconf2-2.1.18/build/install/usr/local/lib/libnetconf2.so  -DLIBNETCONF2_INCLUDE_DIR=/home/hc/netconf/libnetconf2-2.1.18/build/install/usr/local/include  -DSYSREPO_LIBRARY=/home/hc/netconf/sysrepo-2.1.84/build/install/usr/local/lib/libsysrepo.so  -DSYSREPO_INCLUDE_DIR=/home/hc/netconf/sysrepo-2.1.84/build/install/usr/local/include  -DSYSREPOCTL_EXECUTABLE=/home/hc/netconf/sysrepo-2.1.84/build/install/usr/local/bin/sysrepoctl  -DSYSREPOCFG_EXECUTABLE=/home/hc/netconf/sysrepo-2.1.84/build/install/usr/local/bin/sysrepocfg -DOPENSSL_CRYPTO_LIBRARY=/home/hc/netconf/openssl-1.1.1q/install/usr/local/lib/libcrypto.so  -DOPENSSL_INCLUDE_DIR=/home/hc/netconf/openssl-1.1.1q/install/usr/local/include  -DLIBSSH_LIBRARIES=/home/hc/netconf/libssh-0.9.6/build/install/usr/local/lib/libssh.so  -DLIBSSH_INCLUDE_DIRS=/home/hc/netconf/libssh-0.9.6/build/install/usr/local/include  -DOPENSSL_SSL_LIBRARY=/home/hc/netconf/openssl-1.1.1q/install/usr/local/lib/libssl.so ..
-- The C compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- libnetconf2 was compiled with support of up to 6 threads
-- Found CMocka: /usr/lib/x86_64-linux-gnu/libcmocka.so (Required is at least version "1.0.1") 
-- Found Uncrustify: /usr/local/bin/uncrustify (found suitable version "0.75.1_f", minimum required is "0.71") 
-- Found OpenSSL: /home/hc/netconf/openssl-1.1.1q/install/usr/local/lib/libcrypto.so (found version "1.1.1q")  
-- Found LibNETCONF2: /home/hc/netconf/libnetconf2-2.1.18/build/install/usr/local/lib/libnetconf2.so (found suitable version "3.3.2", minimum required is "3.3.0") 
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - not found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - not found
-- Looking for vdprintf
-- Looking for vdprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for getline
-- Looking for getline - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strnstr
-- Looking for strnstr - not found
-- Looking for strdupa
-- Looking for strdupa - found
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    pthread

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CheckTypeSize.cmake:230 (check_include_file)
  /usr/share/cmake-3.16/Modules/TestBigEndian.cmake:33 (CHECK_TYPE_SIZE)
  CMakeModules/UseCompat.cmake:46 (TEST_BIG_ENDIAN)
  CMakeLists.txt:242 (use_compat)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.85.0-DEV")  
-- Found LibSystemd: /usr/lib/x86_64-linux-gnu/libsystemd.so  
-- systemd system service unit path: /home/hc/netconf/netopeer2-2.1.36/build/install/usr/local/lib/systemd/system
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found LibYANG: /home/hc/netconf/libyang-2.0.231/build/install/usr/local/lib/libyang.so (found suitable version "2.22.4", minimum required is "2.21.8") 
-- Found Sysrepo: /home/hc/netconf/sysrepo-2.1.84/build/install/usr/local/lib/libsysrepo.so (found suitable version "7.8.10", minimum required is "7.8.4") 
-- Looking for eaccess
-- Looking for eaccess - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hc/netconf/netopeer2-2.1.36/build
hc@ubuntu:~/netconf/netopeer2-2.1.36/build$ 
hc@ubuntu:~/netconf/netopeer2-2.1.36/build$ make 
Scanning dependencies of target serverobj
[  1%] Building C object CMakeFiles/serverobj.dir/src/common.c.o
In file included from /home/hc/netconf/libnetconf2-2.1.18/build/install/usr/local/include/nc_server.h:33,
                 from /home/hc/netconf/netopeer2-2.1.36/src/common.c:42:
/home/hc/netconf/libnetconf2-2.1.18/build/install/usr/local/include/libnetconf2/session_server.h:28:11: fatal error: openssl/x509.h: No such file or directory
   28 | # include <openssl/x509.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/serverobj.dir/build.make:63: CMakeFiles/serverobj.dir/src/common.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: CMakeFiles/serverobj.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
hc@ubuntu:~/netconf/netopeer2-2.1.36/build$ 
```

**Comment by mx568549060** [comment] 2022-12-05 05:46
libyang (v2.0.231)  libnetconf2 (v2.1.18)  sysrepo (v2.1.84) netopeer2 (v2.1.36)  libssh-0.9.6

Learn form https://github.com/CESNET/netopeer2/issues/1312 , `NC_ENABLED_SSH NC_ENABLED_TLS`  should be enabled .while when I compiling libnetconf2-2.1.18, before I set `LIBSSH_LIBRARIES LIBSSH_INCLUDE_DIRS` it  prompt `Could NOT find LibSSH (missing: LIBSSH_INCLUDE_DIRS LIBSSH_LIBRARIES)`，but after I set `LIBSSH_LIBRARIES LIBSSH_INCLUDE_DIRS` it show nothing about libssh(Neither show `Could NOT find LibSSH` nor show `Found LibSSH` ).

```
hc@ubuntu:~/netconf/libnetconf2-2.1.18/build$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/install/usr/local \
-DOPENSSL_ROOT_DIR=/home/hc/netconf/openssl-1.1.1q/install/usr/local ..
-- The C compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found CMocka: /usr/lib/x86_64-linux-gnu/libcmocka.so (Required is at least version "1.0.1") 
-- Found Uncrustify: /usr/local/bin/uncrustify (found suitable version "0.75.1_f", minimum required is "0.71") 
-- Looking for vdprintf
-- Looking for vdprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for getline
-- Looking for getline - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strnstr
-- Looking for strnstr - not found
-- Looking for strdupa
-- Looking for strdupa - found
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    pthread

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CheckTypeSize.cmake:230 (check_include_file)
  /usr/share/cmake-3.16/Modules/TestBigEndian.cmake:33 (CHECK_TYPE_SIZE)
  CMakeModules/UseCompat.cmake:46 (TEST_BIG_ENDIAN)
  CMakeLists.txt:208 (use_compat)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Found OpenSSL: /home/hc/netconf/openssl-1.1.1q/install/usr/local/lib/libcrypto.so (found version "1.1.1q")  
-- OpenSSL found, required for TLS
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibSSH (missing: LIBSSH_INCLUDE_DIRS LIBSSH_LIBRARIES)
  (Required is at least version "0.7.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibSSH.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:243 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hc/netconf/libnetconf2-2.1.18/build/CMakeFiles/CMakeOutput.log".
See also "/home/hc/netconf/libnetconf2-2.1.18/build/CMakeFiles/CMakeError.log".
hc@ubuntu:~/netconf/libnetconf2-2.1.18/build$ 
hc@ubuntu:~/netconf/libnetconf2-2.1.18/build$ 
hc@ubuntu:~/netconf/libnetconf2-2.1.18/build$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/install/usr/local \
-DOPENSSL_ROOT_DIR=/home/hc/netconf/openssl-1.1.1q/install/usr/local \
-DLIBSSH_LIBRARIES=/home/hc/netconf/libssh-0.9.6/build/install/usr/local/lib/libssh.so \
-DLIBSSH_INCLUDE_DIRS=/home/hc/netconf/libssh-0.9.6/build/install/usr/local/include ..
-- OpenSSL found, required for TLS
-- Found LibPAM: /usr/lib/x86_64-linux-gnu/libpam.so  
-- LibPAM found, version < 1.4, disabled PAM tests
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibYANG (missing: LIBYANG_LIBRARY LIBYANG_INCLUDE_DIR)
  (Required is at least version "2.18.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibYANG.cmake:86 (find_package_handle_standard_args)
  CMakeLists.txt:286 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hc/netconf/libnetconf2-2.1.18/build/CMakeFiles/CMakeOutput.log".
See also "/home/hc/netconf/libnetconf2-2.1.18/build/CMakeFiles/CMakeError.log".
```

I know the if libssh was found,it will log like this:
```
-- OpenSSL found, required for TLS
-- Found LibSSH: /usr/local/include (found suitable version "0.9.6", minimum required is "0.7.1") 
-- Found LibPAM: /usr/lib/x86_64-linux-gnu/libpam.so
```

I don't know  whether the libnetconf2 show nothing about LibSSH effect the `Looking for NC_ENABLED_SSH - not found` in netopeer2 log ?

**Comment by michalvasko** [comment] 2022-12-05 08:22
Duplicate of #1313.

**Closed by michalvasko** 2022-12-05 08:22 UTC
