### ISSUE TITLE
RPC/Action output issue

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#951] opened 2021-07-08 15:05 UTC
Hi!

I've noticed that whenever an RPC or Action returns multiple leaves in its output, the callback never returns.
Maybe it's a libnetconf2 issue, but I could reproduce it using netopeer.

I'll attach the code I've used, it's basically a modified sysrepo example where I subscribe for the tester RPC:

`./rpc_subscibe_example /test:tester`

Then I called the RPC on NETCONF:

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <tester xmlns="urn:com:test"/>
</rpc>
```

Anytime where there was only 1 leaf in the output it worked.

I've used the latest devel of libyang/sysrepo/libnetconf2/netopeer2.

Thanks!
[rpc_output_issue.tar.gz](https://github.com/CESNET/netopeer2/files/6785516/rpc_output_issue.tar.gz)

**Comment by michalvasko** [comment] 2021-07-09 11:39
Most likely a duplicate of https://github.com/CESNET/libnetconf2/issues/317.

**Closed** 2021-08-02 14:20 UTC
Labels: is:bug, status:duplicate
