### ISSUE TITLE
Multiple simultaneous requests to netopeer doesn't get a response 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#77] opened 2016-12-06 18:00 UTC
When multiple requests are sent to connector without waiting for a response from the previous requests, we do not receive any response. For example,
```xml
 < rpc message-id="m-0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 < lock>
    < target>
       < running/>
    < /target>
  < /lock>
  < /rpc>
```
 and
```xml
 < rpc message-id="m-1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  < lock>
   < target>
     < candidate/>
   < /target>
  < /lock>
  < /rpc>
```

RPC requests are sent without waiting for the response for the first lock request, then the response is not received for the second lock request.
If we delay the second request until we get the response for the first request, the second request goes through fine and proper response is received from the connector.

is there any fix available , Looks like we have single thread to handle this

**Comment by michalvasko** [comment] 2016-12-07 12:55
Hi,
a problem caused by the current server architecture. More here #6.

Regards,
Michal

**Comment by vishalwc** [comment] 2016-12-07 13:59
Hi Michal 

The  #6. issue talks about the separate session . but this are the messages on same session , authentication is over ,and would have been buffer in TCP  stack and could be polled and processed one by one by single thread .

the messages above are not at very high rate as well . 
please let me know how it is related to TIME_WAIT

**Comment by michalvasko** [comment] 2016-12-08 11:07
Hi,
you are right and it should be fixed now. However, you should not ignore replies to your RPCs.

Regards,
Michal

**Closed** 2016-12-08 11:07 UTC

**Comment by vishalwc** [comment] 2016-12-08 13:24
Thanks for the update , I will pick up the fix from libnetconf2 master branch . this  issue is with ODL

**Comment by vishalwc** [comment] 2016-12-09 15:02
it just hangs out after hello msg
 
mgr_rpc: deleting timed out request '1'
Error: request to server timed out
yangcli root@10.1.18.86>
mgr_ses: channel read failed on session 1 (a:4) (-1:tranport read)
Error: ses read failed on session 1 (Success)
 
NETOPEER Logs 
Dec  9 02:44:50 VISHAL-CG-18-86 netopeer2-server[15001]: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).

**Comment by michalvasko** [comment] 2016-12-12 11:30
Hi,
can you please try it with the devel branch of libnetconf2 and netopeer2?

Regards,
Michal
