### ISSUE TITLE
Netopeer2-server crashes with get-config command from the Netopeer2-cli

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/Netopeer2#418] opened 2019-04-12 14:55 UTC
Hi,

I have a netopeer2-cli connected to a local netopeer2-server and once I enter a get-config on any of the installed modules' datastore (both startup and running), the server crashes with Segmentation Fault without giving any other details. The server has been started with the debug level 3 but it didn't offer any other useful information on the log:

Please note that I have been able to get/edit the same module's datastore through sysrepocfg though. I have posted the logs for them, below:
(1) Netopeer2-server:
**sudo netopeer2-server -d -v 3**
```
[INF]: Accepted a connection on 0.0.0.0:830.
[2019/04/12 10:44:23.280237, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/04/12 10:44:23.281447, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.8.90
[2019/04/12 10:44:23.281461, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.8.90
[2019/04/12 10:44:23.282610, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,ssh-rsa,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256,hmac-sha2-256,none,none,,
[2019/04/12 10:44:23.358099, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2019/04/12 10:44:23.358486, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/04/12 10:44:23.365793, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/04/12 10:44:23.365926, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2019/04/12 10:44:23.375599, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[2019/04/12 10:44:23.419583, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[INF]: User "netconf" authenticated.
[INF]: Received an SSH message "request-channel-open" of subtype "session".
[INF]: Received an SSH message "request-channel" of subtype "subsystem".
[2019/04/12 10:44:26.548082, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
[2019/04/12 10:44:26.548599, 2] channel_rcv_change_window:  Adding 1216950 bytes to channel (43:43) (from 61054 bytes)
[INF]: Generated new event (netconf-session-start).
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 4 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 2 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 4 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 4 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 4 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 2 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 2 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 2 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 2 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 1 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 0 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 4 event new RPC.
```
After the Netopeer2-cli sends: 
```
> connect --host localhost --login netconf
Interactive SSH Authentication
Type your password:
Password:

> get-config --source startup  --filter-xpath /ietf-interfaces:interfaces
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
```

**The server crashes with the below error on its log: **
```
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
Segmentation fault (core dumped)
Segmentation fault (core dumped)
```
 Meanwhile, from sysrepocfg, I have been able to edit and get the datastore to be printed too. So, it does not seem to be related to the module, but somehow related to **SSH channel poll error** as it says on the cli's output? 
**sudo sysrepocfg -d startup -g "/ietf-interfaces:interfaces/*" --format xml**
```xml
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
  </interface>
  <interface>
    <name>eth1</name>
  </interface>
  <interface>
    <name>vlan1</name>
  </interface>
</interfaces>
```
Any help would be appreciated. @michalvasko  Sorry to bother you again :)

**Comment by michalvasko** [comment] 2019-04-15 11:09
Hi,
that is a strange error and there is no debugging information whatsoever (SSH error is related to the server crashing, nothing else). However, my guess would be just some problem with library versions or something similar. Have you updated some dependency recently?

Regards,
Michal

**Comment by dwdrajesh** [comment] 2019-04-15 14:04
No Michal, i haven't updated anything lately. I wanted to check the sysrepo log now , which is the default syslog file sysrepo Release build logs the error on? I will try to restart sysrepo on the log level 4 and try to check the syslog output. Is it  on /var/log/messages by default? I dont see anything getting logged there. Thanks

**Comment by dwdrajesh** [comment] 2019-04-15 14:34
Hi @michalvasko , I was trying to rerun this issue after I restarted all my applications. I noticed a strange error on the netopeer2-server's logs as soon as it is started and it is trying to read from sysrepod. Here is what it says:

[ERR]: The leafref leaf is config but refers to a non-config leaf. (/o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints/name)
[ERR]: Module "o-ran-uplane-conf" parsing failed.

And here are the nodes in the yang module "**o-ran-uplane-conf**" that the error is referring to, 


    list **static-low-level-tx-endpoints** {
      key name;
      config false;
      description
        "Object model for static-low-level-tx-endpoints configuration";

      leaf name {
        type string;

        description
          "Unique name of static-low-level-tx-endpoints object.";
      }
.......
}

    list **low-level-tx-endpoints** {
      key "name";

      description
        "Object model for low-level-tx-endpoints configuration - augmented static-low-level-tx-endpoints by local-address
        which cannot be added to static low-level-tx-endpoints as we cannot have modificable element in static object";

      leaf name {
        type leafref {
          path "/user-plane-configuration/static-low-level-tx-endpoints/name";
          require-instance false;
        }
        mandatory true;

        description
          "Unique name of low-level-tx-endpoint object. Reference to static object";
      }
............
}

In essence, the '**name**' node in **low-level-tx-endpoints** refers to the '**name**' node in **static-low-level-tx-endpoints** but since it is a '**require-instance false**', the error "**leafref leaf is config but refers to a non-config leaf**" should not occur. I remember seeing a similar issue on the Github issue list and it was fixed in the sysrepo library I assume. I am using the latest build however.

**Comment by michalvasko** [comment] 2019-04-16 08:46
Hi,
I have looked at the code at it seem fine to me, the warning should not occur in your case, so can you please provide the whole module so that I can reproduce it?

Regards,
Michal

**Comment by dwdrajesh** [comment] 2019-04-16 11:58
Hi Michal, Thanks. 
The module is the o-ran-uplane-conf.yang specified in the O-RAN interface. Now, I am not entirely sure if this is publicly shareable without signing up to their licensing agreement  which can be found at: 
[o-ran-uplane-conf.txt](https://github.com/CESNET/Netopeer2/files/3084791/o-ran-uplane-conf.txt)

https://www.o-ran.org/specification-access . If you have any issue with getting the module, please let me know and please check the attached file for the module I am having issue with.  Thanks

**Comment by michalvasko** [comment] 2019-04-16 14:15
Hi,
what version of *libyang* and other applications are you using? I failed to reproduce the problem with the current *libyang.

Regards,
Michal

**Comment by dwdrajesh** [comment] 2019-04-16 14:35
Hi Michal,
I am using libyang version libyang.so.0.16.92 , sysrepod version 0.7.7, netopeer2-server 0.7.1 and netopeer2-cli 2.0.50. Since I do not see this issue with sysrepo daemon and sysrepocfg alone (just updating the datastore through sysrepocfg seems fine without involving netopeer2), I suspect there might be something wrong in how sysrepo is notifying netopeer2-server. That was the only log I have available though. 

Thanks,
Rajesh

**Comment by michalvasko** [comment] 2019-04-17 06:18
Hi Rajesh,
it would be best if you could properly install current versions of all the software (having uninstalled the previous ones) and then try again. I think you should not see any issue that way.

Regards,
Michal

**Comment by dwdrajesh** [comment] 2019-04-17 19:15
Hi Michal,
I will try to install the new versions and try again. I was just wondering what would be the best and safest way to remove/clear all the datastore files at /etc/sysrepo/data? I am just worried that manually deleting those files might create other unintended problems as I know from my experience before. I noticed there are quite a number of .startup, .running and .lock files there which do not update even after I update my datastore through the "sysrepocfg" command. So, in short, I am running sysrepocfg --editor=vim   --datastore=startup "module_name" and modifying the startup datastore and I get a success. But if I query the startup datastore again after restarting my sysrepo daemon, I get the previous values back (which means the .startup file wasn't modified). 

Thanks,
Rajesh

**Comment by michalvasko** [comment] 2019-04-18 07:45
Hi Rajesh,
that is weird that your `startup` changes are not persistent but it could be caused by having 2 overlapping *sysrepo* installations. You should be able to just remove the data files, but you can simply use `make uninstall_with_repo` in *sysrepo* to have everything removed.

Regards,
Michal

**Comment by brchiu** [comment] 2019-06-21 15:20
@dwdrajesh  & @michalvasko , it seems that this problem comes from that `libyang` does not handle absent `config` statement of yin format well. 

You can use `yang2yin` to convert this `o-ran-uplane-conf.yang` to `yin` format, let's say 'o-ran-uplane-conf.yin'. Then process this `o-ran-uplane-conf.yin` with `yanglint`, you can reproduce it without `netopeer2-server` involved.

After traced with gdb, I found the difference of processing yang version (`yanglint o-ran-uplane-conf.yang` ) and yin version (`yanglint o-ran-uplane-conf.yin`) is at :  
```
int
lys_leaf_add_leafref_target(struct lys_node_leaf *leafref_target, struct lys_node *leafref)
{
...
    /* check for config flag */
    if (((struct lys_node_leaf*)leafref)->type.info.lref.req != -1 &&
            (leafref->flags & LYS_CONFIG_W) && (leafref_target->flags & LYS_CONFIG_R)) {
        LOGVAL(ctx, LYE_SPEC, LY_VLOG_LYS, leafref,
               "The leafref %s is config but refers to a non-config %s.",
               strnodetype(leafref->nodetype), strnodetype(leafref_target->nodetype));
        return -1;
    }
```
For `yang` format case, `((struct lys_node_leaf*)leafref)->type.info.lref.req` is `-1`, but for `yin` format case, `((struct lys_node_leaf*)leafref)->type.info.lref.req` is `0` and pass the `if` check and print the aforementioned  message.

It looks like `yang_read_require_instance()` will set this value properly but `parser_yin.c` seems just leave `lref.req` as initialized `0` value.

**Comment by dwdrajesh** [comment] 2019-06-21 15:32
Hi @brchiu , I was getting this error with yang format file as well, so not sure if this is related to yin only.

**Comment by brchiu** [comment] 2019-06-21 15:48
@dwdrajesh, though you install yang file to sysrepo, but certain module, sorry I forgot which one, strangely read internal data with yin format, so you got this error. That's why I try to isolate the problem using a single `yanglint` utility to verdict it instead of complex interaction between `netopeer2-cli` , `sysrepod` and `libyang`.

**Comment by brchiu** [comment] 2019-06-27 13:20
@dwdrajesh & @michalvasko

With the following change, 
```
static int
np2srv_init_schemas(void)
{
....
        } else if (!np2srv_sr_get_schema(np2srv.sr_sess.srs, schemas[i].module_name,
                schemas[i].revision.revision, NULL, SR_SCHEMA_YIN, &data, NULL)) {
            mod = lys_parse_mem(np2srv.ly_ctx, data, LYS_IN_YIN);
            free(data);
```
==>
```

        } else if (!np2srv_sr_get_schema(np2srv.sr_sess.srs, schemas[i].module_name,
                schemas[i].revision.revision, NULL, SR_SCHEMA_YANG, &data, NULL)) {
            mod = lys_parse_mem(np2srv.ly_ctx, data, LYS_IN_YANG);
            free(data);
```
you can temporarily eliminate the aforementioned error message :
```
[ERR]: The leafref leaf is config but refers to a non-config leaf. (/o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints/name)
[ERR]: Module "o-ran-uplane-conf" parsing failed.
```

that's why I think the handling of yin format is culprit and do the above test.

**Comment by michalvasko** [comment] 2019-06-28 06:27
Hi,
if someone can provide all the import models of `o-ran-uplane-conf` (I cannot load it without them) then I could try to take a look at the problem.

Regards,
Michal

**Comment by brchiu** [comment] 2019-06-28 10:46
@michalvasko , here is : https://drive.google.com/open?id=1yeHMpqTEHnN7VZBsfmgs9aPan4NwIFH9

**Comment by michalvasko** [comment] 2019-07-01 06:58
Hi,
thanks for the models and debugging, it should be fixed now.

Regards,
Michal

**Closed** 2019-07-01 06:58 UTC

**Comment by himaniadsar** [comment] 2021-03-16 08:56
Hi,
How to get sys logs in Netopeer 2 at run time?

Regards,
Himani
