### ISSUE TITLE
Configure Netopeer Server for Session idle timout

### ISSUE THREAD

**Issue by VishalGujela** [CESNET/netopeer2#1681] opened 2024-12-13 12:07 UTC
Hi @michalvasko 
I have a query regarding configuring netopeer sever in a way where i can set the session idle timeout as per my requirement.
If we can do that can you guide me how to do it.
Else let me know if we cant.
Thanks
Vishal

**Comment by VishalGujela** [comment] 2024-12-14 06:33
Hi @michalvasko 
Input :
**<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server" xmlns:ct="urn:ietf:params:xml:ns:yang:ietf-crypto-types">
  <listen>
    <idle-timeout>0</idle-timeout>
    <endpoints>
      <endpoint>
        <name>default-ssh</name>
        <ssh>
          <tcp-server-parameters>
            <local-address>0.0.0.0</local-address>
          </tcp-server-parameters>
          <ssh-server-parameters>
            <server-identity>
              <host-key>
                <name>default-key</name>
                <public-key>
                  <central-keystore-reference>genkey</central-keystore-reference>
                </public-key>
              </host-key>
            </server-identity>
            <client-authentication>
              <users>
                <user>
                  <name>amantya</name>
                  <public-keys>
                    <inline-definition>
                      <public-key>
                        <name>amantya-authorized-key</name>
                        <public-key-format xmlns:ct="urn:ietf:params:xml:ns:yang:ietf-crypto-types">ct:ssh-public-key-format</public-key-format>
                        <public-key>$PUBLIC_KEY</public-key>
                      </public-key>
                    </inline-definition>
                  </public-keys>
                </user>
              </users>
            </client-authentication>
          </ssh-server-parameters>
        </ssh>
      </endpoint>
    </endpoints>
  </listen>
</netconf-server>**
this is my xml configuration file to configure netconf server as per rfc we can se if we set idle-timeout to zero the server will never loose it's connection with client .
Please help me to understand this 
Output : 
**[INF]: LN: Accepted a connection on 0.0.0.0:830 from 172.17.0.1:42884.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "publickey".
[INF]: LN: Received an SSH message "request-auth" of subtype "publickey".
[INF]: LN: User "amantya" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[ERR]: LN: Session 2: Client <hello> timeout elapsed.**
Im getting this output from server.

**Comment by michalvasko** [comment] 2024-12-16 10:58
What *libnetconf2*/*netopeer2* version are you using? There was a problem with this timeout some time ago.

**Comment by VishalGujela** [comment] 2024-12-16 10:59
Hi 
these are the versions im using : netopeer2-2.2.28  libnetconf2-3.3.3

**Comment by michalvasko** [comment] 2024-12-16 11:10
I think this may be caused by a *libssh* bug and a workaround was committed (976d11a5e1fe2539260f60204e3e570af76368e8) in *libnetconf2* 3.3.5.

**Comment by VishalGujela** [comment] 2024-12-16 11:12
do i need to keep this configuration same as i have shared ?
And also i followed rfc "https://datatracker.ietf.org/doc/html/draft-ietf-netconf-netconf-client-server-02#page-38"
in this the yang model is different for netconf server.

**Comment by michalvasko** [comment] 2024-12-16 11:33
The configuration is fine and it was not a released version, you can update simply to [3.5.1](https://github.com/CESNET/libnetconf2/releases).

**Comment by VishalGujela** [comment] 2024-12-16 11:36
I guess if i will update libnetconf version then i also have to update libyang and so on.
That might be gave me hard time coz i have been using this library in my codebase.
Thanks anyways,
Will let you know if i will face any issue

**Comment by michalvasko** [comment] 2024-12-16 12:28
Or you can simply use the single commit https://github.com/CESNET/libnetconf2/commit/976d11a5e1fe2539260f60204e3e570af76368e8, up to you.

**Closed by michalvasko** 2024-12-16 12:28 UTC
Labels: is:bug, status:invalid
