### ISSUE TITLE
ERROR: Communication socket unexpectedly closed (libssh)

### ISSUE THREAD

**Issue by naveenchaubey** [CESNET/Netopeer2#301] opened 2018-07-25 04:04 UTC
Hi,
   
   I'm using Netopeer2 server with my onos client. When i connected to the client I'm getting error below. 
   
  

VERBOSE: Accepted a connection on 0.0.0.0:830.
[2018/07/25 09:29:31.190078, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-SSHD-UNKNOWN
[2018/07/25 09:29:31.190100, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-SSHD-UNKNOWN
[2018/07/25 09:29:31.196641, 2] ssh_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2018/07/25 09:29:31.196702, 2] ssh_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2018/07/25 09:29:31.204195, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
VERBOSE: Received an SSH message "request-service" of subtype "ssh-userauth".
VERBOSE: Received an SSH message "request-auth" of subtype "none".
VERBOSE: Received an SSH message "request-auth" of subtype "publickey".
VERBOSE: User "sdn" tried to use an unknown (unauthorized) public key.
VERBOSE: Failed user "sdn" authentication attempt (#1).
VERBOSE: Received an SSH message "request-auth" of subtype "interactive".
[2018/07/25 09:29:31.311094, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
VERBOSE: Failed user "sdn" authentication attempt (#2).
VERBOSE: Received an SSH message "request-auth" of subtype "interactive".
VERBOSE: User "sdn" authenticated.
VERBOSE: Received an SSH message "request-auth" of subtype "interactive".
ERROR: User "sdn" authenticated, but requested another authentication.
VERBOSE: Received an SSH message "request-channel-open" of subtype "session".
[2018/07/25 09:29:31.316603, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2018/07/25 09:29:31.316628, 1] ssh_socket_exception_callback:  Socket error: disconnected
ERROR: Communication socket unexpectedly closed (libssh).

**Comment by michalvasko** [comment] 2018-08-01 13:48
Hi,
most likely a duplicate of #299.

Regards,
Michal

**Closed** 2018-08-01 13:49 UTC
Labels: duplicate
