### ISSUE TITLE
 user-rpc gets an error message of 'leafref  points to a non-existing leaf'

### ISSUE THREAD

**Issue by yaxueXu** [CESNET/netopeer2#522] opened 2020-01-10 07:27 UTC
Hi,
I need to send a rpc which inculdes leafref(config fasle ), but get error message. 

The software-install rpc has a leaf slot-name,  whose type is leafref, and defined in container software-inventory;  the container software-inventory is a 'config false' container.

I have provided this software-inventory using a sr_dp_get_items_cb callback (set by sr_dp_get_items_subscribe()), so the client can get software-inventory information by 'get --filter-xpath /xran-software-management:software-inventory'.
But when send 'user-rpc  --content install.xml', an error message is output.

the sippnet of xran-software-management.yang is as belew:

rpc software-install {
    description
      "Install a previously downloaded software package.";

    input {
      leaf slot-name {
        type leafref {
          path "/software-inventory/software-slot/name";
          }
        must "/software-inventory/software-slot[name = current()][active = 'false' and running = 'false']" {
          error-message "software-install may be requested only against active::false and running::false slot!";
        }
        mandatory true;

        description
          "software-slot to which the software shall be installed to.";
      }

      leaf-list file-names {
        type string;

        description
          "Names of the files within software package to be installed";
      }
    }
    output {
      leaf status {
        type enumeration {
          enum STARTED {
            description
              "Operation has been started without error.";
          }
          enum FAILED {
            description
              "Operation cannot be started because of error, more detailed information can be found in error-message.";
          }
        }
        mandatory true;

        description
          "Status of the software package install.";
      }
      leaf error-message {
        when "../status = 'FAILED'";
        type string;

        description
          "Detailed error Message when the status is failed.";
      }
    }
  }
container software-inventory {
    config false;
    description
      "Contains information about each software slot and its content.";

    list software-slot {
      key name;
      min-elements 2;

      description
        "Information about available software-slots and their software.";

      leaf name {
        type string;

        description
          "Name of the software package. This shall be unique to identify the software-slot.";
      }

      leaf status {
        type enumeration {
          enum VALID {
            description
              "Slot Contains software build considered as proven valid";
          }
          enum INVALID {
            description
              "software build is not currently used by RU. The software is considered by RU as damaged (e.g. wrong CRC)";
          }
          enum EMPTY {
            description
              "W slot does not contain software package.";
          }
        }
        config false;
        mandatory true;

        description "Indicates the status of the software slot";
      }

      leaf active {
          type boolean;
      must "../status = 'VALID'";
        config false;
          description
            "informs if software stored in particular slot is activated at the moment";
      }

      leaf running {
          type boolean;
      must "../status = 'VALID'";
        config false;
          description
            "informs if software stored in particular slot is used at the moment";
      }

      leaf access {
        type enumeration {
          enum READ_ONLY {
            description
              "slot intended only for factory software,
              activation of such software slot means getting back to factory defaults";
          }
          enum READ_WRITE {
            description
              "slot used for updating software";
          }
        }
        default READ_WRITE;
        config false;

        description
          "Indicates the writability of the slot.
          A Read-Only software slot is one which has a factory installed software-slot";
      }

      leaf product-code {
        type leafref {
		path "/hw:hardware/hw:component/xran-hw:product-code";
		}
        config false;

        description "product code provided by the vendor, specific to the product. This is derived from manifest file.";
      }

      leaf vendor-code {
        type string {
          length 1..2;
        }
        config false;

        description
          "Unique code of the vendor. This is derived from manifest file.";
      }

      leaf build-id {
        type string;
        config false;

        description
          "Identity associated with the software build. This is derived from manifest file.";
      }

      leaf build-name {
        type string;
        config false;

        description
          "Name of the build. This is derived from manifest file.";
      }

      leaf build-version {
        type leafref{
		path "/hw:hardware/hw:component/hw:software-rev";
		}
        description "Version of the software build. This is derived from manifest file.";
      }

      list files {
        key "name";
        config false;

        description "List of all the files present in the software package.";

        leaf name {
          type string;

          description
            "Name of the file installed in the slot.";
        }

        leaf version {
          type string;

          description
            "Version of the file installed in the slot";
        }
        leaf local-path {
          type string;
          mandatory true;

          description
            "Complete path of the file stored locally";
        }

        leaf integrity {
          type enumeration {
            enum OK {
              description "OK - indicates that file integrity is correct";
            }
            enum NOK {
              description "NOK - indicates corrupted file";
            }
          }
          config false;

          description
            "Result of the file integrity check (checksum calculation) during installation.";
        }
      }
    }
  }

<pre><font color="#75507B"> </font>./netopeer2-cli                                                           <font color="#4E9A06">15:17:42</font> 
&gt; connect
Interactive SSH Authentication
Type your password:
Password: 
&gt; get --filter-xpath /xran-software-management:software-inventory
DATA
&lt;software-inventory xmlns=&quot;urn:xran:software-management:1.0&quot;&gt;
  &lt;software-slot&gt;
    &lt;name&gt;SOFTWARE_SLOT1_RUNNING&lt;/name&gt;
    &lt;status&gt;INVALID&lt;/status&gt;
    &lt;active&gt;true&lt;/active&gt;
    &lt;running&gt;true&lt;/running&gt;
    &lt;access&gt;READ_WRITE&lt;/access&gt;
    &lt;product-code&gt;HPRU&lt;/product-code&gt;
    &lt;vendor-code&gt;SW&lt;/vendor-code&gt;
    &lt;build-id&gt;sw&lt;/build-id&gt;
    &lt;build-name&gt;sunwave crossfire&lt;/build-name&gt;
    &lt;build-version&gt;V1.0&lt;/build-version&gt;
  &lt;/software-slot&gt;
  &lt;software-slot&gt;
    &lt;name&gt;SOFTWARE_SLOT2_CANDIDATE&lt;/name&gt;
    &lt;status&gt;VALID&lt;/status&gt;
    &lt;active&gt;false&lt;/active&gt;
    &lt;running&gt;false&lt;/running&gt;
    &lt;access&gt;READ_WRITE&lt;/access&gt;
    &lt;product-code&gt;HPRU&lt;/product-code&gt;
    &lt;vendor-code&gt;SW&lt;/vendor-code&gt;
    &lt;build-id&gt;sw&lt;/build-id&gt;
    &lt;build-name&gt;sunwave crossfire&lt;/build-name&gt;
    &lt;build-version&gt;V1.0&lt;/build-version&gt;
  &lt;/software-slot&gt;
&lt;/software-inventory&gt;
</pre>

<pre>&gt; 
&gt; user-rpc  --content install.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /xran-software-management:software-install/slot-name
	message:  Leafref &quot;/software-inventory/software-slot/name&quot; of value &quot;SOFTWARE_SLOT2_CANDIDATE&quot; points to a non-existing leaf.
</pre>

the install.xml is as below:
<pre>&lt;software-install xmlns=&quot;urn:xran:software-management:1.0&quot;&gt;
&lt;slot-name&gt;SOFTWARE_SLOT2_CANDIDATE&lt;/slot-name&gt;
&lt;/software-install&gt;
</pre>

--------- netopeer2-server  log ：
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 2: thread 0 event new RPC.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: There is no leafref "/software-inventory/software-slot/name" with the value "SOFTWARE_SLOT2_CANDIDATE", but it is not required.
VERBOSE: Must condition "/software-inventory/software-slot[name = current()][active = 'false' and running = 'false']" not satisfied, but it is not required.
VERBOSE: All data nodes and constraints resolved.
ERROR: (cl_rpc_send:3154) Error by processing of the request.

callback code :
static int data_provider_cb_software_management(const char *xpath, sr_val_t **values, size_t *values_cnt,
       								 uint64_t request_id, const char *original_xpath, void *private_ctx)
{
	
	sr_val_t *v = NULL;
	unsigned int v_cnt;
    int rc = SR_ERR_OK;
	unsigned int slot;
	unsigned char slot_num = 2;  /*at least 2 software slots*/
	v_cnt =slot_num*per_slot_element_cnt;

	printf("%s\r\n",xpath);
	rc = sr_new_values(v_cnt, &v);
    if (SR_ERR_OK != rc) 
	{
        return rc;
    }
	for(slot=0;slot<slot_num;slot++)
	{
		fill_base_element_value(v,slot);
		fill_files_value(v,slot);
	}
	
	for (size_t i = 0; i < v_cnt; ++i) 
	{
        sr_print_val(v+i);
    }
	
	*values = v;
    *values_cnt = v_cnt;

	return rc;
}

static int data_requester(sr_session_ctx_t *session);

int data_provider_software_management_subscribe_register(sr_session_ctx_t *session)
{
	sr_subscription_ctx_t *subscription = NULL;
	int rc = SR_ERR_OK;
	if(SR_ERR_OK != (rc=sr_dp_get_items_subscribe(session, Software_Management, 
		data_provider_cb_software_management, NULL, SR_SUBSCR_DEFAULT, &subscription)))
	{
		 fprintf(stderr, "%s occurs error(%s) when registering for software management subscribe.\r\n", Software_Management, sr_strerror(rc));
	}
}

Thanks & Regards，
yaxue

**Comment by michalvasko** [comment] 2020-01-10 09:17
Hi,
I see you are using the old *sysrepo* and *netopeer2* and I believe this use-case was simply not supported there. Please use the current *sysrepo* and *netopeer2*.

Regards,
Michal

**Comment by yaxueXu** [comment] 2020-01-10 10:15
Hi Michal,
Thanks for your response. 
I will use the current  sysrepo and netopeer2.

Can you help me to check whether the sequence I used for this rpc software-install is correct? 
1) Providing this software-inventory using a sr_dp_get_items_cb callback (set by sr_dp_get_items_subscribe()), so that client can get;
2) client  gets software-inventory by 'get --filter-xpath /xran-software-management:software-inventory';
3)client sends  user-rpc  --content install.xml

Thanks & Regards，
yaxue

**Comment by michalvasko** [comment] 2020-01-10 10:23
Hi,
in the old *sysrepo*/*netopeer2* there was no other way of providing state data, so yes, it is correct. The problem is that they are not used for any validation, just for returning to clients if they request it (by `get`, for instance). This was fixed in the new *sysrepo*.

Regards,
Michal

**Closed** 2020-05-15 06:57 UTC

**Comment by michalvasko** [comment] 2020-10-14 14:12
Hi,
you had best create a new issue with detailed description of your use-case, I will not be able to help you otherwise.
