### ISSUE TITLE
Configuration Modification Not Successful

### ISSUE THREAD

**Issue by Lllyh69** [CESNET/netopeer2#1587] opened 2024-06-13 03:29 UTC
Hi,
I encountered an issue when attempting to modify the configuration. Initially, I initialized a part of the "ieee802-dot1q-bridge" model as follows:
```
> get-config --source running --filter-xpath //ieee802-dot1q-bridge:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>br1</name>
      <address>d6-ad-62-c5-49-ae</address>
      <bridge-type>provider-edge-bridge</bridge-type>
    </bridge>
  </bridges>
</data>
```

However, when I tried to use `edit-config` to modify the "address" to "d7-ad-62-c5-49-ae", I encountered some issues:
```
> edit-config --target running --config=ietf-mac-cfg.xml
OK
> 
notification (2024-06-13T11:00:48.643094137+08:00)
<netconf-config-change xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications">
  <changed-by>
    <username>root</username>
    <session-id>0</session-id>
  </changed-by>
  <datastore>running</datastore>
  <edit>
    <target xmlns:dot1q="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">/dot1q:bridges/dot1q:bridge[dot1q:name='br1']/dot1q:address</target>
    <operation>replace</operation>
  </edit>
</netconf-config-change>
```

Server Logs:
```
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 processing (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: EV ORIGIN: "ieee802-dot1q-bridge" "change" ID 2 priority 0 for 1 subscribers published.
[INF]: SR: EV ORIGIN: "ieee802-dot1q-bridge" "change" ID 2 priority 0 succeeded.
[INF]: SR: EV ORIGIN: "ieee802-dot1q-bridge" "done" ID 2 priority 0 for 1 subscribers published.
[INF]: SR: EV ORIGIN: "ieee802-dot1q-bridge" "done" ID 2 priority 0 succeeded.
[INF]: SR: EV ORIGIN: "ietf-netconf-notifications" "notif" ID 7 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV LISTEN: "ietf-netconf-notifications" "notif" ID 7 processing.
[INF]: SR: EV LISTEN: "ietf-netconf-notifications" "notif" ID 7 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 succeeded.
[INF]: NP: Session 2: thread 1 event new RPC.
```
Listener Output:
```
 ========== EVENT change CHANGES: ====================================

MODIFIED: /ieee802-dot1q-bridge:bridges/bridge[name='br1']/address = d6-ad-62-c5-49-ae
to /ieee802-dot1q-bridge:bridges/bridge[name='br1']/address = d7-ad-62-c5-49-ae

 ========== END OF CHANGES =======================================

 ========== EVENT done CHANGES: ====================================

MODIFIED: /ieee802-dot1q-bridge:bridges/bridge[name='br1']/address = d6-ad-62-c5-49-ae
to /ieee802-dot1q-bridge:bridges/bridge[name='br1']/address = d7-ad-62-c5-49-ae

 ========== END OF CHANGES =======================================

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========

/ieee802-dot1q-bridge:bridges (container)
/ieee802-dot1q-bridge:bridges/bridge[name='br1'] (list instance)
/ieee802-dot1q-bridge:bridges/bridge[name='br1']/name = br1
/ieee802-dot1q-bridge:bridges/bridge[name='br1']/address = d6-ad-62-c5-49-ae
/ieee802-dot1q-bridge:bridges/bridge[name='br1']/bridge-type = ieee802-dot1q-bridge:provider-edge-bridge
```

I find that the configuration changes did not succeed, but there is no indication of what went wrong. Please help me.

Thanks！！

**Comment by satomhxl** [comment] 2024-06-13 06:30
I update netopeer2 to the latest release these days, and I encountered the same problem,

**Comment by michalvasko** [comment] 2024-06-13 08:06
You are right that the value in the output is the old one for some reason but everything else looks fine, quite strange. Can you actually check the value, using `sysrepocfg -X`, for example?

**Comment by Lllyh69** [comment] 2024-06-13 09:02
It is my xml:`ietf-mac-cfg.xml`
```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge"
	xmlns:brtc="urn:nxp:dn:storage:yang:nxp-bridge-vlan-tc-flower"
	xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<bridge>
		<name>br1</name>
		<bridge-type>provider-edge-bridge</bridge-type>
		<address nc:operation="replace">d7-ad-62-c5-49-ae</address>
	</bridge>
</bridges>
```
If I use：
`sysrepocfg -d running -m ieee802-dot1q-bridge -X`

I still get the old output：`d6-ad-62-c5-49-ae`
```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
  <bridge>
    <name>br1</name>
    <address>d6-ad-62-c5-49-ae</address>
    <bridge-type>provider-edge-bridge</bridge-type>
  </bridge>
</bridges>
```
However, I was able to modify the value of `l` in the `examples.yang` with some operations。I also think it is quite strange!

**Comment by michalvasko** [comment] 2024-06-13 09:41
This must be some incompatibility on your end, mixed *sysrepo* installations or something similar, it does not make sense.

**Comment by satomhxl** [comment] 2024-06-13 13:24
Is there any method to debug this issue?
I think I've uninstall the old version of sysrepo, by executing `make uninstall` and `make clean`.
And `which sysrepocfg` and `which sysrepoctl` only output one path.
`sysrepocfg -V` is "sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.2.170 (SO v7.24.11)"

Now I can successfully change the sysrepo running datastore by
```
sysrepocfg --edit=something.xml
```
But I can't change the sysrepo running datastore by the command below in netopeer2-cli
```
edit-config --target running --config=something.xml
```

**Comment by Lllyh69** [comment] 2024-06-14 01:13
I can also change the sysrepo running datastore by:

`sysrepocfg  --edit=$FILE -d running -f xml -m ieee802-dot1q-bridge -v2`

But I can't change the sysrepo running datastore by:`edit-config`

**Comment by michalvasko** [comment] 2024-06-14 06:41
I am sorry but I am not able to help, I have never seen such an issue and since it occurred after updating, it must be caused by the old version, somehow.

**Comment by Lllyh69** [comment] 2024-06-14 07:39
But I haven't downloaded the old version, I've been using the latest version since the beginning.
This question is so confusing to me.

**Comment by michalvasko** [comment] 2024-06-14 08:04
The only explanation is that `netopeer2-server` is linked with a different *sysrepo* than `sysrepocfg`, I cannot help with that. But if you are certain your setup is correct, try using a fresh VM and install everything from scratch. If it does not work this way, post your exact installation steps so that I can reproduce it.

**Comment by Lllyh69** [comment] 2024-06-18 01:18
I have reinstalled netoppeer2 with a new VM as you suggested, and I still have the problem of not being able to modify the configuration data.
Here are my steps to install netoppeer2:
I used Ubuntu22.04 LTS
Download the latest versions of netopeer2, libyang, sysrepo, libnetconf2.
Compile libyang --> libnetconf2 --> sysrepo.
```
unzip  netopeer2.zip
unzip  libyang.zip
unzip  sysrepo.zip
unzip  libnetconf2.zip

cd  libyang
Mkdir build
cd  build
Cmake ..
make
sudo make install
cd

cd  libnetconf2
Mkdir build
cd  build
Cmake ..
make
sudo make install
cd

cd  sysrepo
Mkdir build
cd  build
Cmake ..
make
sudo make install
cd
```

After compiling, add the lib library to the system lib.
```
sudo ln -s /usr/local/lib/libsysrepo.so.7 /lib/
sudo ln -s /usr/local/lib/libnetconf2.so.4 /lib/
sudo ln -s /usr/local/lib/libyang.so.3 /lib/
```

Finally, compile netopeer2.
```
cd  netopeer2
Mkdir build
cd  build
Cmake ..
make
sudo make install
```

The only problem is that in` cmake.. ` During the process, occurred `Not Found Uncrusity`, but still successfully compiled.
After compiling netoppeer2 can also implement` netopeer2_test`, everything is fine.
Then I installed `ieee802-dot1q-bridge` and `other yang models`, shut down the NACM service, and the above problems occurred.

**Comment by michalvasko** [comment] 2024-06-18 06:11
Sorry, I forgot to ask you to try using the current `devel` branches instead of `master`, there were some issues in this release (although I do not think as severe as this) that should be fixed now.

**Comment by Lllyh69** [comment] 2024-06-18 08:23
Do netopeer2, libyang, libnetconf2, sysrepo all need to install the `devel`branches？

**Comment by michalvasko** [comment] 2024-06-18 08:25
Yes, ideally, to prevent any problems.

**Comment by Lllyh69** [comment] 2024-06-20 01:52
Thank you! 
I used the `devel` version of sysrepo and netopeer2, and now I can successfully modify the configuration by `edit-config`!

**Closed** 2024-06-20 05:58 UTC
Labels: is:bug, status:invalid
