### ISSUE TITLE
handshake does not work when multiple sessions are created for the same ssh connection

### ISSUE THREAD

**Issue by RavikumarTulugu** [CESNET/Netopeer2#185] opened 2017-10-16 05:13 UTC
handshake does not work when multiple sessions are created for the same ssh connection, we are trying to create multiple netconf sessions on the same ssh connection. The first netconf session goes through fine, we can see the capabilities and the hello reply back from server. however, the second session does not send the hello reply message back to the client, the client keeps on waiting for the reply message which never happens. I am using 0.9-r1 release. Please advise. I am pasting the logs from netopeer server to confirm this. I am using the latest git clone of netopeer2 server.

netopeer2-server[9027]: Accepted a connection on 0.0.0.0:830.
[2017/10/13 07:19:42.992085, 1] ssh_server_connection_callback: SSH client banner: SSH-2.0-Ganymed_262
[2017/10/13 07:19:42.992542, 1] ssh_analyze_banner: Analyzing banner: SSH-2.0-Ganymed_262
[2017/10/13 07:19:44.418126, 2] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
netopeer2-server[9027]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[9027]: Received an SSH message "request-auth" of subtype "none".
netopeer2-server[9027]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[9027]: User "root" authenticated.
netopeer2-server[9027]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[9027]: Received an SSH message "request-channel" of subtype "subsystem".
netopeer2-server[9027]: Session 4: sending message:
urn:ietf:params:netconf:base:1.0urn:ietf:params:netconf:base:1.1urn:ietf:params:netconf:capability:writable-running:1.0urn:ietf:params:netconf:capability:candidate:1.0urn:ietf:params:netconf:capability:rollback-on-error:1.0urn:ietf:params:netconf:capability:validate:1.1urn:ietf:params:netconf:capability:startup:1.0urn:ietf:params:netconf:capability:xpath:1.0urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all,report-all-tagged,trim,expliciturn:ietf:params:netconf:capability:notification:1.0urn:ietf:params:netconf:capability:interleave:1.0
netopeer2-server[9027]: Session 4: sending message:
urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&revision=2016-08-05urn:ietf:params:xml:ns:yang:1?module=yang&revision=2017-02-20urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&revision=2013-07-15urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&revision=2013-07-15urn:ietf:params:xml:ns:yang:ietf-yang-library?module=ietf-yang-library&revision=2016-06-21&module-set-id=25urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&revision=2012-02-22urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&revision=2011-06-01&features=writable-running,candidate,rollback-on-error,validate,startup,xpathurn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&revision=2012-02-06
netopeer2-server[9027]: Session 4: sending message:
urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&revision=2008-07-14urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&revision=2008-07-14http://example.net/turing-machine?module=turing-machine&amp;revision=2013-12-27urn:ietf:params:xml:ns:yang:ietf-interfaces?module=ietf-interfaces&revision=2014-05-08urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&revision=2014-05-08urn:ietf:params:xml:ns:yang:ietf-ip?module=ietf-ip&revision=2014-06-16urn:ietf:params:xml:ns:yang:ietf-keystore?module=ietf-keystore&revision=2016-10-31urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&revision=2014-12-10urn:ietf:params:xml:ns:yang:ietf-ssh-server?module=ietf-ssh-server&revision=2016-11-02
netopeer2-server[9027]: Session 4: sending message:
urn:ietf:params:xml:ns:yang:ietf-tls-server?module=ietf-tls-server&revision=2016-11-02urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&revision=2016-11-02&features=listen,ssh-listen,tls-listen,call-home,ssh-call-home,tls-call-homeurn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&revision=2014-08-06urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&revision=2014-08-06&features=authentication,local-usershttp://mavenir.com/ns/MainConfig/1.1?module=MainConfig&amp;revision=2016-08-08urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&revision=2011-06-014
netopeer2-server[9027]: Session 4: sending message:
]]>]]>
[2017/10/13 07:19:45.986075, 2] grow_window: growing window (channel 43:100) to 1280000 bytes
netopeer2-server[9027]: Session 4: received message:
urn:ietf:params:netconf:base:1.0

netopeer2-server[9027]: Sending session-start request.
netopeer2-server[9027]: session-start request sent, waiting for response.
netopeer2-server[9027]: session-start response received, processing.
netopeer2-server[9027]: Sending event-notification request.
netopeer2-server[9027]: event-notification request sent, waiting for response.
netopeer2-server[9027]: event-notification response received, processing.
netopeer2-server[9027]: Generated new event (netconf-session-start).
netopeer2-server[9027]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[9027]: Received an SSH message "request-channel" of subtype "subsystem".

**Comment by michalvasko** [comment] 2017-10-18 12:32
Duplicate of [libnetconf2#44](https://github.com/CESNET/libnetconf2/issues/44).

**Closed by michalvasko** 2017-10-18 12:32 UTC
