### ISSUE TITLE
Query: does netopeer2 support YANG schema mount (RFC 8528)

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#761] opened 2020-11-19 04:39 UTC
Hi,
Does the latest netopeer2, libyang, etc. support a Schema Mount (RFC 8528)? If not are there plans to add this support?
Regards,
Igor

**Comment by michalvasko** [comment] 2020-11-19 09:03
Duplicate of https://github.com/CESNET/libyang/issues/691

**Closed by michalvasko** 2020-11-19 09:03 UTC
