### ISSUE TITLE
cli print "malformed message" error when execute get-schema command

### ISSUE THREAD

**Issue by qmm161** [CESNET/Netopeer2#18] opened 2016-08-22 12:43 UTC
cli print these two error when execute "get-schema --model ietf-netconf-with-defaults"
ly ERROR: Invalid NameStartChar of the attribute.
nc ERROR: Session 5: malformed message received.

**Comment by rkrejci** [comment] 2016-08-23 10:56
The problem is in libyang when it prints anyxml content. Since the issue is internally quite complex, it will be fixed in devel branch (0.10.x) together with adding anydata support.

**Comment by qmm161** [comment] 2016-08-23 12:35
I think netopeer server escape the xml charactor after calling  lys_print_mem would be better. The lys_print_mem does not know it's caller will fill the module text to xml body. 
The yang model text may have '<' or '&' character in the contact statement or description of any leaf.

**Comment by rkrejci** [comment] 2016-08-23 13:29
This would solve just this particular issue, but the problem is in a way how libyang stores data in anyxml. It does not know if the stored data are XML data or not and therefore it is unknown if the data are supposed to be escaped or not.

**Comment by qmm161** [comment] 2016-08-24 08:53
I still don't know why this issue has any relationship with the way how libyang stores data in anyxml. I tried to call a escape xml function in nc_clb_default_get_schema in libnetconf2 (after the line lys_print_mem(&model_data, module, LYS_OUT_YANG, NULL); ) and got this bug fixed. Should I commit these codes to libnetconf2?

**Comment by rkrejci** [comment] 2016-08-24 10:31
That solves this issue, but the generic problem is, that it is unclear what kind of data are expected in `lyd_node_anyxml->value.str`. With your patch, you would store the escaped data. In get-config callback, we store dumped xml string into anyxml node. In this case, the tags are not supposed to be escaped (escaping would break reading the rpc-reply on the client side). So there is inconsistence.

The solution, I'm currently working on, is to declare, that the `str` member is supposed to contain only non-xml data, so when the anyxml is being printed as XML, it is escaped (now, it's not). Besides this, I'm also extending possibility of value formats that can be stored in anyxml/anydata - string, lyxml_node*, lyd_node*. The non-string formats will allow to store xml based data that are not supposed to be stored in string format.

**Comment by rkrejci** [comment] 2016-08-24 13:47
The issue is fixed with the current devel branches of libyang (0.10.56), libnetconf2 (0.7.12) and Netopeer2 server (0.2.13). sysrepo is not yet updated, but it shouldn't take much time.

**Closed by rkrejci** 2016-08-24 13:47 UTC

**Comment by dmcpriv** [comment] 2016-09-26 23:05
It is called anyxml, so it is assumed to be XML data.  I don't think anyxml should be escaped by the YANG library.  If the content needs to be escaped because it is a string, the server should escape it first, no?  I now see no way to provide a raw XML string as a value since it all being escaped.  I don't really see the need to take a big XML string and put it into a tree format just to get the same string back out.

**Comment by rkrejci** [comment] 2016-09-27 07:58
Please keep this discussion in CESNET/libyang#106
