### ISSUE TITLE
netopeer2-cli can't connect to netopeer2-server on the same machine.

### ISSUE THREAD

**Issue by OlympusHo** [CESNET/netopeer2#424] opened 2019-04-23 06:32 UTC
1.client log:
root@olympus-VirtualBox:/home/olympus# netopeer2-cli 
> connect 
nc ERROR: Starting the SSH session failed (Public key from server (rsa-sha2-512) doesn't match user preference (ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ssh-rsa,ssh-dss)).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
> 
2.server log:
[INF]: Accepted a connection on 0.0.0.0:830.
[2019/04/23 14:22:16.238235, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/04/23 14:22:16.241904, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.8.90
[2019/04/23 14:22:16.241947, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.8.90
[2019/04/23 14:22:16.243698, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,ssh-rsa,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256,hmac-sha2-256,none,none,,
[2019/04/23 14:22:16.313088, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2019/04/23 14:22:16.313863, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2019/04/23 14:22:16.327811, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2019/04/23 14:22:16.329985, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
[2019/04/23 14:22:16.330055, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
[ERR]: Communication SSH socket unexpectedly closed.

**Comment by michalvasko** [comment] 2019-04-24 06:37
Hi,
seems to me it is a duplicate of #381, what version of *libnetconf2* are you using?

Regards,
Michal

**Comment by OlympusHo** [comment] 2019-04-24 07:20
Thanks for your reply!
The version of  libnetconf2  is seems to 0.12.45,    the commit id is 7e5f7b0

**Comment by OlympusHo** [comment] 2019-04-24 07:21
> Hi,
> seems to me it is a duplicate of #381, what version of _libnetconf2_ are you using?
> 
> Regards,
> Michal

Thanks for your reply!
The version of libnetconf2 is seems to 0.12.45, the commit id is 7e5f7b0

**Comment by michalvasko** [comment] 2019-04-24 07:29
Hi,
that seems fine. Then I would blame your *libssh* version, 0.8.9 is probably the version of the current `master`, it is not an official release. If it does not work with the official 0.8.7 release then I will try to investigate more.

Regards,
Michal

**Comment by OlympusHo** [comment] 2019-04-24 07:37
> Hi,
> that seems fine. Then I would blame your _libssh_ version, 0.8.9 is probably the version of the current `master`, it is not an official release. If it does not work with the official 0.8.7 release then I will try to investigate more.
> 
> Regards,
> Michal

I use the libssh-0.7.7.tar.gz,  not the 0.8.7 release

Regards,
Olympus

**Comment by michalvasko** [comment] 2019-04-24 09:07
Hi Olympus,
the log you provided says otherwise, so maybe you have several *libssh* versions installed on your system.

Regards,
Michal

**Closed** 2020-05-15 06:38 UTC
