### ISSUE TITLE
Netopeer2-server crash during long running configuration

### ISSUE THREAD

**Issue by frimpler** [CESNET/netopeer2#901] opened 2021-05-19 11:35 UTC
Hi Michal,

We observed crashes of netopeer2-server during the process of applying huge configurations. The details have been analyzed, already, and we have created patches to avoid the crash. 
As you know, there is an association between nc_session and sr_session (via nc_id, ->np_get_user_sess()) when changes will be delivered to the sysrepo-subscriptions. If the nc_session drops for some reasons during processing the subscription-callback the nc_session data become stale. When the callback returns, it wants to access those data which lead to the crash.

The patche introduce a reference count and the nc_session won't be deleted as long as it is referenced:
https://github.com/frimpler/Netopeer2/tree/early_session_delete
https://github.com/frimpler/libnetconf2/tree/early_session_delete

I'm not sure, if this is the way you'd prefer to fix it. If yes, tell me and I'll create two PRs.

Regards,
Frank

**Comment by michalvasko** [comment] 2021-05-20 06:34
Thanks for providing your fixes but I do not think it is necessary to add a whole new mechanism just to handle this situation. But you are right, the problem seems to still be present so I have tried to fix it with this [patch](https://github.com/CESNET/netopeer2/files/6513428/server.patch.txt). Since you have tried fixing it yourself, I will try to justify why no session should be prematurely freed anymore and maybe you can point me to something I am missing.

Issue occurs only when a *netopeer2-server* callback is being called while the NETCONF session is dropped, which is picked up by another thread that deletes both NETCONF and *sysrepo* session. When a NC session is being polled, its [RPC lock is held](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server.c#L1606). If an RPC is actually received, it is [kept](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server.c#L1659) until a [reply has been sent](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server.c#L1728). So the RPC lock must be held on the session the whole time the [global RPC callback](https://github.com/CESNET/netopeer2/blob/devel/src/main.c#L709) (which calls specific RPC callbacks) is [executing](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server.c#L1373).

Based on all this, the NETCONF session cannot be freed while an RPC callback is executing because it always [takes the RPC lock](https://github.com/CESNET/libnetconf2/blob/devel/src/session.c#L610) first (or prints an error after [timeout](https://github.com/CESNET/libnetconf2/blob/devel/src/session_p.h#L318)). But timeout of 1s seems like not much so it may need to be increased to maybe 10s, what do you think? In any case, if the NETCONF session is freed before the *sysrepo* session as in the patch, no invalid situation should occur under normal circumstances.

**Comment by frimpler** [comment] 2021-05-20 11:56
Unfortunately, the provided patch does not prevent the netopeer2-server from crashing. I guess, the problem is the assumption, that the module-change callbacks return in time. But they don't - which comes on top of the nc-session drop (I told you...we deal with a huge amount of data). The rpc-lock for an nc-session doesn't care about a still running event(-session) in sysrepo's worker-thread.

**Comment by michalvasko** [comment] 2021-05-20 12:57
> The rpc-lock for an nc-session doesn't care about a still running event(-session) in sysrepo's worker-thread.

I do not understand, with the patch the NETCONF session cannot be freed until the RPC lock is held. And *sysrepo* session cannot be freed until NETCONF session is not freed. Or did the RPC lock timeout elapse when freeing the NETCONF session, have you actually seen the error message? If not, then I still do not understand, please explain where exactly is the fault in my logic.

**Comment by frimpler** [comment] 2021-05-20 13:21
see the attached snippet (which shows the messages, but I had to remove some parts, like timestamps etc.)
[drop-session.txt](https://github.com/CESNET/netopeer2/files/6516182/drop-session.txt)

**Comment by michalvasko** [comment] 2021-05-20 14:19
That did not really help me understand the exact problem. It may be best to reproduce it, so what exactly is happening? While the first change callback is executing, the session is dropped and once the callback returns and all the following events are handled, it crashes?

**Comment by frimpler** [comment] 2021-05-20 14:35
Yes, it is as you concluded. I'm not sure, how we can come together. The point is, my patch works for sure (it's tested), because it keeps track of the references. No matter what happens with the NETCONF session. The crashes happens in different parts of the code but mostly [here](https://github.com/sysrepo/sysrepo/blob/d869c7ce7114b9437e6aa47d06ccc448e18bef0d/src/sysrepo.c#L2201) right after returning from the module-change callback. And the reason is of course, that the address where session points to has stale content.

**Comment by michalvasko** [comment] 2021-05-21 07:38
Okay, after reproducing it I have understood the problem. As long as *netopeer2-server* timeout parameter is set correctly meaning it is enough for no *sysrepo* callbacks to timeout, my patch seems to be working. However, when it is not, the server "finishes" callback processing by the timeout and there is no way anymore to learn that there is still a callback executing. I would say this is mostly an invalid situation on the side of the user but at the same time ideally should not result in a crash.

> my patch works for sure (it's tested)

So these are my problems with your solution. Firstly, you have solved *netopeer2* problem in *libnetconf2*. I always try to avoid such solutions if at all possible, it just makes the projects less independent and bloated. Then, there is still ["the assumption, that the module-change callbacks return in time"](https://github.com/frimpler/Netopeer2/commit/538cb45e1228282daca094115dea7de21a5cb38d#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176R1015) (having criticized my patch for this). Lastly, I do not really think it would be working if you also had some subscriptions on the session because the NETCONF session is also [referenced and used](https://github.com/CESNET/netopeer2/blob/devel/src/netconf.c#L1090) asynchronously in *sysrepo* notification callbacks but I have not actually tested this.

Having said that, I think you can actually create PRs and I will merge them. The reason is that several related things were changed in the latest `libyang2` *netopeer2* and implementing 2 proper fixes for both versions seems redundant. So you can fix it in the current versions and I will come up with a solution for the new versions (which are almost ready to be released).

**Comment by frimpler** [comment] 2021-05-21 08:44
Ok, the first PR is started. 
BTW: 
I'm far from criticizing (your) or defending (my) solutions. That's mainly your written SW and you decide how you do things and that's also the reason why we discuss it in a ticket (and not in a PR).

Regards,
Frank

**Comment by michalvasko** [comment] 2021-05-21 08:59
No problem :) It just seemed to me you were reluctant to discuss the problem in more detail but it was needed.

**Comment by michalvasko** [comment] 2021-05-21 14:51
Okay, so now it should be fixed in both `devel` and `libyang2` branches.

**Comment by frimpler** [comment] 2021-05-26 06:24
Thank you!

**Closed** 2021-05-26 08:27 UTC
Labels: is:bug, status:completed
