### ISSUE TITLE
netopeer2 installation fails

### ISSUE THREAD

**Issue by umbertino** [CESNET/netopeer2#768] opened 2020-11-26 08:23 UTC
Hi,

after having successfully installed sysrepo on a native Linux machine as well as on an ARM-based Raspi I'm facing problems doing so on Ubuntu-based Virtual machine. libyang, libnetconf2 and sysrepo can be installed flawlessly. Issuing `sudo make install` ends up with permission issues. Here is the console output:

```
.
.
.
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Installing: /usr/local/bin/netopeer2-server
-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Installing missing sysrepo modules...
[ERR]: Failed to open "/dev/shm/sr_ietf-netconf-acm.running" (Permission denied).
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to apply changes (Operation failed)
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 1


make: *** [Makefile:86: install] Error 1
```
Tried to clean the shared memory and re-installed but didn't succeed. Tried to hack a bit on the shared memory permissions but didn't succeed neither. 
Does anyone have an idea? I'd be very grateful for any help. Thanks!

Cheers,

umbertino

**Comment by michalvasko** [comment] 2020-11-26 08:25
Duplicate of https://github.com/sysrepo/sysrepo/issues/2080.

**Closed by michalvasko** 2020-11-26 08:25 UTC
