### ISSUE TITLE
Callhome: idle callhome session not getting cleaned up after 'idle-timeout' seconds 

### ISSUE THREAD

**Issue by senrajib** [CESNET/Netopeer2#142] opened 2017-05-18 09:10 UTC
Hi Michal
We are observing for persistent(or periodic) connection type idle call home sessions aren't getting cleaned up after 'idle-timeout' seconds .  Would you please clarify on this behavior?

I could see in source code, idle callhome sessions are getting marked as timed out depending on  the time last rpc was received, but don't see it getting cleaned up .

-Rajib

**Comment by michalvasko** [comment] 2017-05-18 12:51
Hi Rajib,
you mean the session gets invalidated, but is not cleaned up? *libnetconf2* cannot just clean those sessions up because it passes them to the application that uses them, it could lead to some unexpected behavior. You can easily cleanup your `struct pollsession` yourself using `nc_ps_clear()` (read its documentation first!), for example.

Regards,
Michal

**Comment by senrajib** [comment] 2017-05-18 14:14
Hi Michal
I just wanted to verify if idle-timeout parameter works as per data model. I had one established callhome connection kept idle for a long time. idle-timeout was configured as 10 minutes. I was expecting that callhome connection to get dropped after 10 minutes or so. But that didn't happen.

I was exploring netopeer2-server and libnetconf2 source code to  only to find idle callhome sessions are getting marked as timed out depending on the time last rpc was received(nc_ps_poll/nc_server_ch_client_thread_session_cond_wait), but don't see it getting cleaned up anywhere  from netopeer2-server code.

Our application doesn't link to libnetconf2/netopeer2 , so we don't have access to those sessions. We only expected Netopeer2-server to clean up those identified idle sessions to conform with 'idle-timeout' description specified in ietf-netconf-server.yang data model.

-Rajib

**Comment by michalvasko** [comment] 2017-05-19 08:50
Hi Rajib,
you are right, should be fixed by cesnet/libnetconf2@1ff977678671ddcb64d8cb2efa97e78517cbc866 (I referenced it incorrectly).

Regards,
Michal

**Closed by michalvasko** 2017-05-19 08:50 UTC
