### ISSUE TITLE
Netopeer2-server -t flag for timeout

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1338] opened 2023-01-25 14:16 UTC
Hi Michal,

One query related to timeout flag, if system/device time changes while server is running, will this affect the server timeouts. We are facing issue related to timeouts in get command while system time changes in middle.

Regards,
Ankit

**Comment by michalvasko** [comment] 2023-01-25 15:04
Sadly, `pthread_mutex_timedlock()` can only work with `CLOCK_REALTIME` so yes, time adjustments will cause it to misbehave. However, there seems to be a fairly new function `pthread_mutex_clocklock()` available so I will try to add optional support for it in *sysrepo* (where the problem actually is) once I finish my current tasks.

**Comment by ankit7gup** [comment] 2023-01-27 06:42
Sure, Thanks! Will wait for the update.

**Comment by ankit7gup** [comment] 2023-02-06 13:24
Hi Michal,

I have tested the changes. Seems like it works for the get/edit-config RPCs but is still failing for subscribe/create-subscription.
There is a 10-minute time jump, and timeout is received.

Pasting logs for reference.

Feb  6 09:37:55  netopeer2-server[1249]: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
Feb  6 09:37:55 netopeer2-server[1249]: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
Feb  6 09:47:51  netopeer2-server[1249]: Callback event "rpc" with ID 1 processing timed out.
Feb  6 09:47:51  netopeer2-server[1249]: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
Feb  6 09:47:51  netopeer2-server[1249]: Published event "abort" "/notifications:create-subscription" with ID 1 priority 5 for 1 subscribers.
Feb  6 09:47:51  netopeer2-server[1249]: User callback failed.
Feb  6 09:47:51  netopeer2-server[1249]: Failed to send an RPC (User callback failed).
Feb  6 09:47:51  netopeer2-server[1249]: Session 1: thread 3 event new RPC.
Feb  6 09:47:51  netopeer2-server[1249]: Session 1: thread 3 event reply error.


Kindly suggest.

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment] 2023-02-06 14:55
I did not think you would encounter the same problem in *libnetconf2* but I think that is to blame. But it should be fixed as well, so try again with the latest *libnetconf2* devel.

**Comment by ankit7gup** [comment] 2023-02-07 17:18
Hi Michal,

It seems to be working. Thanks!

Just wanted to know, if you can share the expected time for next official release, so that I can plan an upgrade accordingly.

Regards,
Ankit

**Comment by michalvasko** [comment] 2023-02-08 07:35
I'd like to help but our releases are not exactly scheduled. I would expect in a month or so, definitely not sooner.

**Comment by ankit7gup** [comment] 2023-02-10 08:36
Ok, Thanks Michal. Will await till then.
Apart from this while doing some regression tests, I observed below error while doing create-subscription. Any suggestion on this?

[INF]: LN: Trying to connect via IPv4 to 10.0.2.16:4334.
[INF]: LN: Successfully connected to 10.0.2.16:4334 over IPv4.
[INF]: SR: Session 1512 (user "root", CID 120) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "publickey".
[INF]: NP: User "root" has no authorized_keys file.
[INF]: LN: Failed user "root" authentication attempt (#1).
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
**[ERR]: LN: Session 1: Inactive read timeout elapsed.**
[INF]: LN: Trying to connect via IPv4 to 10.0.2.16:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 10.0.2.16:4334.


Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment] 2023-02-10 11:22
Can you reliably reproduce it? Can you provide the steps?

**Comment by ankit7gup** [comment] 2023-02-13 04:48
> Can you reliably reproduce it? Can you provide the steps?

So, In this case multiple steps are being executed repeatedly, which includes connecting to server, subscribe for notifications, get data, edit-config operations. All operations are happening in loop. 3 out of 10 times this error is observed. On running same steps individually error is not there.

**Comment by michalvasko** [comment] 2023-02-13 10:48
It is not ideal that the use-case is more complex but still, please provide the exact steps performed in the loop.

**Comment by ankit7gup** [comment] 2023-02-13 11:19
Loop steps as follows: 
1. SSH Callhome is performed.
2. Create-subscription is executed.
3. Get-data is performed.
4. Edit-config is done.
5. Get-data is performed.
6. Edit-config is done.
7. Get-data is performed.
8. Edit-config is done.
9. Close session is executed.

**Comment by michalvasko** [comment] 2023-02-13 13:59
What NETCONF client are you using? How are you disconnecting the sessions, can you provide a larger part of the output?

**Comment by ankit7gup** [comment] 2023-02-14 06:19
> What NETCONF client are you using? How are you disconnecting the sessions, can you provide a larger part of the output?

We are using opensource pyhton based NcClient as netconf client.
For the logs, I am sharing complete file, for netopeer2.
[Uploading netopeer2_logs.txt…]()

**Comment by michalvasko** [comment] 2023-02-14 10:03
Please reupload the logs, they are not available.

**Comment by ankit7gup** [comment] 2023-02-14 10:13
[netopeer2_logs.txt](https://github.com/CESNET/netopeer2/files/10731275/netopeer2_logs.txt)

**Comment by michalvasko** [comment] 2023-02-14 11:13
The output is really weird, what *libnetconf2* version are you using? I would like to fix this problem if possible but note that I am quite sure it is not harmful in anyway, it seems there are problems in fully terminating the NETCONF sessions, nothing else.

**Comment by ankit7gup** [comment] 2023-02-14 11:38
Hi, I have taken the monotonic clock changes manually on a rather earlier version of ibnetconf2. Related to terminating Netconf sessions, also found that while doing close-session sometimes port is not released, as observed in pcap when using Netconf client and server on different hosts connected via switch.

**Comment by michalvasko** [comment] 2023-02-14 12:01
As long as you are not using the latest version it is impossible for me to guess whether I have already fixed it or not so you will have to update if you want out support.

**Comment by ankit7gup** [comment] 2023-02-27 09:07
Hi Michal, 
When can we expect the new release to be available. Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment] 2023-02-27 09:15
Sorry, but I am unable to tell you. May be a few weeks or a month.

**Comment by ankit7gup** [comment] 2023-02-27 10:07
Ok, thanks!

**Closed** 2023-03-17 13:13 UTC
Labels: is:enhancement, status:completed

**Comment by rsys-smalagin** [comment] 2025-03-06 18:13
Hi Michel ,
I am facing similar issue, manual execution works fine. 
When write golang program with hello message followed by GET RPC throwing below error in docker logs, Any suggestions for this ?

[INF]: LN: Accepted a connection on 0.0.0.0:830 from 172.17.0.1:55314.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "labadmin" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: NP: Generated new event (netconf-session-start).
[ERR]: LN: Session 3: Inactive read timeout elapsed.
[INF]: NP: Session 3: thread 1 event session terminated.
[INF]: NP: Generated new event (netconf-session-end).

**Comment by michalvasko** [comment] 2025-03-10 08:21
Generally, you should not write into closed issues but create a new issue instead. This tends to happen with NETCONF clients that do not format the messages properly, what client are you using?

**Comment by rsys-smalagin** [comment] 2025-03-10 09:20
Sorry Michel that. 
I am using go-netconf-client (https://github.com/openshift-telco/go-netconf-client/tree/v1.0.6) to communicate Netopeer2 server. 

Regards
Shiva

**Comment by michalvasko** [comment] 2025-03-10 09:29
Then I must blame the client for incorrect formatting. But if you run the server as `netopeer2-server -d -c MSG`, you should see the exact data the client is sending and if you post it here, I should be able to determine the exact issue.

**Comment by rsys-smalagin** [comment] 2025-03-10 09:54
Okay.  Here is the message , 

netopeer2-server -d -c MSG

[INF]: SR: Connection 3 created.
[ERR]: SR: RPC subscription for "/ietf-netconf:get-config" with priority 0 already exists.
[ERR]: NP: Subscribing for "/ietf-netconf:get-config" RPC failed (Invalid argument).
[ERR]: NP: Server RPC subscribe failed.
[INF]: NP: Server terminated.
[INF]: SR: Connection 3 destroyed.

**Comment by michalvasko** [comment] 2025-03-10 10:01
You have another *netopeer2-server* instance already running, you need to terminate it to get rid of this error.

**Comment by rsys-smalagin** [comment] 2025-03-17 12:43
Thanks Michel. It is working.
